### ISSUE TITLE
通过第三方解析直播源进行播放，播放一会会停止报错，使用GSYVideoPlayer等库可以播放，不知播放器区别在哪

### ISSUE THREAD

**Issue by wangfeng19930909** [dueeeke/DKVideoPlayer#102]
09-07 14:17:29.709 19787-19901/com.lwd.phdyw E/IJKMEDIA: Stream ends prematurely at 724, should be 745
    Stream ends prematurely at 724, should be 745
09-07 14:17:29.758 19787-19901/com.lwd.phdyw E/IJKMEDIA: Option ijkiomanager not found.
09-07 14:17:29.786 19787-19901/com.lwd.phdyw E/IJKMEDIA: Invalid NAL unit 0, skipping.

**Comment by dueeeke** [comment]
给个地址
