### ISSUE TITLE
按照 demo写, 全屏播放后,沉浸式状态栏会变成白色

### ISSUE THREAD

**Issue by SaltedFishkk** [dueeeke/DKVideoPlayer#108]
添加RotateInFullscreenController 控制器,全屏播放后退出来沉浸式状态栏变白色...

**Comment by dueeeke** [comment]
你是怎么实现沉浸式的

**Comment by cmj1314** [comment]
> 添加RotateInFullscreenController控制器，全屏播放后退出来沉浸式状态栏变白色...

这个你解决了吗？我也有遇到

**Comment by cmj1314** [comment]
BaseActivity里添加ViewStatusBarPlace，,全屏播放后退出来会再添加一个默认状态栏，会把ViewStatusBarPlace挤下去

**Comment by vincecarterhu** [comment]
横竖屏切换之后导致状态栏多了一个白条，可以修改 WindowUtil 的showNavigationBar 方法具体代码如下：`    private static void showNavigationBar(Context context) {


        View decorView = scanForActivity(context).getWindow().getDecorView();
        int uiOptions = View.SYSTEM_UI_FLAG_VISIBLE|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION;
        decorView.setSystemUiVisibility(uiOptions);



    }`

**Comment by dueeeke** [comment]
试试新版
