### ISSUE TITLE
提两个建议

### ISSUE THREAD

**Issue by iYang9683** [dueeeke/DKVideoPlayer#111]
1.竖屏模式也能手势操作
2.左右滑动调节进度的手感不好，你的做法是计算滑动的距离除以屏幕宽度，拿这个百分比乘视频的总长度，就是快进的距离。短视频没什么问题，那种一两个小时的视频，轻轻滑动都会跳很远的距离。最好做成：（滑动距离/屏幕宽度）x 90或者120秒

**Comment by dueeeke** [comment]
建议2已经改进，建议1 我暂不采纳，感觉意义不大
