### ISSUE TITLE
如果给播放器换皮肤

### ISSUE THREAD

**Issue by yuan520521** [dueeeke/DKVideoPlayer#119]
如题，我想把开始按钮的图片改下颜色，或者给进度条改下样式，请问该如何做？

**Comment by fujiangren** [comment]
这个重写就好了吧

**Comment by yuan520521** [comment]
不是很明白啊。能仔细说下吗？
或者给个案例。

**Comment by dueeeke** [comment]
在你自己的项目中values-colors中定义一条名为dkplayer_theme_color的resource，就能覆盖掉library中的默认的主题色
