### ISSUE TITLE
关于全屏播放，退出全屏后屏幕旋转的问题

### ISSUE THREAD

**Issue by suxueqiang** [dueeeke/DKVideoPlayer#124]
我的APP是横屏显示的pad版本，视频全屏后退出全屏，项目会切换到竖屏显示。请问这怎么解决呢？

**Comment by dueeeke** [comment]
重写doStartStopFullScreen方法，去除旋转屏幕相关代码即可 https://github.com/dueeeke/dkplayer/blob/master/dkplayer-java/src/main/java/com/dueeeke/videoplayer/controller/BaseVideoController.java#L133
