### ISSUE TITLE
请问怎么去掉4g网络的提示：“您正在使用移动网络。。。”

### ISSUE THREAD

**Issue by CodeMAI** [dueeeke/DKVideoPlayer#130]
请问怎么去掉4g网络的提示：“您正在使用移动网络。。。”

**Comment by dueeeke** [comment]
继承IjkVideoView，重写  checkNetwork()方法，直接return false

**Comment by CodeMAI** [comment]
谢谢

**Comment by CodeMAI** [comment]
> 继承IjkVideoView，重写 checkNetwork()方法，直接return false

谢谢
