### ISSUE TITLE
解码部分的源码能提供么

### ISSUE THREAD

**Issue by fujiangren** [dueeeke/DKVideoPlayer#132]
十分感谢作者的无私奉献  so 库的源码能提供下么

**Comment by dueeeke** [comment]
https://github.com/Bilibili/ijkplayer

**Comment by hnyer** [comment]
> https://github.com/Bilibili/ijkplayer


你好 ， 从 ijkplayer 代码直接编译出来的so能否 替换你这个项目的so文件  。

**Comment by fujiangren** [comment]
不太清楚 没有 没有尝试

**Comment by hnyer** [comment]
> 不太清楚 没有 没有尝试


方便提供 dkplayer 中用到的so的源码 吗

**Comment by dueeeke** [comment]
@hnyer 可以的
