### ISSUE TITLE
m3u8直播源播放一段时间后提示出了点小问题

### ISSUE THREAD

**Issue by loveJYQ** [dueeeke/DKVideoPlayer#135]
Log如下：
![9freb wv8v3 wt o_dta6vs](https://user-images.githubusercontent.com/22961321/48593096-42c69480-e986-11e8-94e2-31e21a394746.png)
直播地址：http://223.110.243.155:80/PLTV/3/224/3221227166/1.m3u8

**Comment by huijiawanquba** [comment]
视频资源有问题
