### ISSUE TITLE
播放状态监听

### ISSUE THREAD

**Issue by AndroidKid19** [dueeeke/DKVideoPlayer#155]
视频播放时一个循环播放的视频怎么监听播放一遍完成

**Comment by dueeeke** [comment]
使用OnVideoViewStateChangeListener

**Comment by csh159** [comment]
一个循环播放的视频，播放完成不回调STATE_PLAYBACK_COMPLETED状态，直接是STATE_BUFFERING 跟STATE_BUFFERED

**Comment by dueeeke** [comment]
@csh159 给个地址
