### ISSUE TITLE
请问，怎么在recyclerView无声播放

### ISSUE THREAD

**Issue by jingzz1** [dueeeke/DKVideoPlayer#158]
需要在recyc;erView时无声播放，全屏时有声播放，请问该怎么做？

**Comment by dueeeke** [comment]
viewholder中添加如下代码
            ijkVideoView.addOnVideoViewStateChangeListener(new OnVideoViewStateChangeListener() {
                @Override
                public void onPlayerStateChanged(int playerState) {
                    if (playerState == IjkVideoView.PLAYER_FULL_SCREEN) {
                        ijkVideoView.setMute(false);
                    } else if (playerState == IjkVideoView.PLAYER_NORMAL) {
                        ijkVideoView.setMute(true);
                    }
                }

                @Override
                public void onPlayStateChanged(int playState) {
                    //小屏状态下播放出来之后，把声音关闭
                    if (playState == IjkVideoView.STATE_PREPARED && !ijkVideoView.isFullScreen()) {
                        ijkVideoView.setMute(true);
                    }
                }
            });
