### ISSUE TITLE
你好，请问抖音Demo中如何给每一个播放页添加一个标题

### ISSUE THREAD

**Issue by gaofeng7777** [dueeeke/DKVideoPlayer#164]
你好，请问抖音Demo中如何给每一个播放页添加一个标题，我在TikTokAdapter中的item_tik_tok中添加了标题TextView,但是不显示，好像是被video覆盖了，请问有什么方法可以解决这个问题？

**Comment by dueeeke** [comment]
不能添加到布局的FrameLayout中，因为这个FrameLayout是专门用来放播放器的
