### ISSUE TITLE
可否预载至缓存呢

### ISSUE THREAD

**Issue by mingchaogui** [dueeeke/DKVideoPlayer#165]

**Comment by dueeeke** [comment]
具体描述下

**Comment by mingchaogui** [comment]
> 具体描述下

直接缓存视频但不开始播放

**Comment by liweiGe** [comment]
我也想知道这个,这样预先缓存在列表播放的时候就会快一点,或者之前看到有人重新改写了内核的网络请求为okhttp的,这两个优化我感觉对列表视频的起播速度会有大幅度提升 @dueeeke 有实现思路吗?类似于xia'mia下面这样
![image](https://user-images.githubusercontent.com/25901728/57346555-7ccc6280-7181-11e9-9b25-f905e9608e2e.png)
