### ISSUE TITLE
请问如何旋转画面

### ISSUE THREAD

**Issue by hyl87** [dueeeke/DKVideoPlayer#166]

**Comment by dueeeke** [comment]
请具体描述

**Comment by hyl87** [comment]
@dueeeke 就是单纯的视频画面旋转,如90,180度旋转

**Comment by dueeeke** [comment]
目前还不支持画面旋转，但是你可以继承IjkVideoView,增加如下方法，即可达到你的需求
    public void setRotation(float rotation) {
        if (mTextureView != null) {
            mTextureView.setRotation(rotation);
            mTextureView.requestLayout();
        }

        if (mSurfaceView != null) {
            mSurfaceView.setRotation(rotation);
            mSurfaceView.requestLayout();
        }
    }

**Comment by ldxyzhou** [comment]
我试了 不生效
