### ISSUE TITLE
字幕、声音 异常

### ISSUE THREAD

**Issue by hnyer** [dueeeke/DKVideoPlayer#168]
null

**Comment by hnyer** [comment]
用 作者 demo中的  MediaPlayer、ExoPlayer 试了  有一些还是不行 。

**Comment by hnyer** [comment]
我暂时的解决办法是 播放视屏的时候 就调用 另外安装的 vlc 播放器。 （有很多视屏播放不了 只能这样搞了，暂时不使用当前这个库了）  。  如果有哪位大佬知道了解决办法 @ 我一下 ，谢谢。

**Comment by dueeeke** [comment]
1.修改module-lite.sh,重新编译so,增加不支持的解码格式
2.用一些第三方播放去实现AbstractPlayer,比如vitamio，vlc-android等
