### ISSUE TITLE
视频上下有黑边，很难受

### ISSUE THREAD

**Issue by assion** [dueeeke/DKVideoPlayer#170]

**Comment by dueeeke** [comment]
请具体描述

**Comment by assion** [comment]
我写的是视频列表页，没有用你项目中的微缩图，用了你的视频控件，我在写了一张图片作为微缩图显示（因为项目中有其他作用），写的视频列表滚动自动播放，我写好之后，滚动到视频item,自动播放的时候，图片隐藏，视频播放，结果视频不会填充满（高度），上下会有挺小的黑线（几个像素左右，看着很不舒服），我已经做了让视频和图片高度保持一致了

**Comment by dueeeke** [comment]
视频显示区域的宽高和IjkVideoView的宽高是独立的，视频显示区域是一个TextureView, 而IjkVideoView是一个FrameLayout, TextureView是居中放置在FrameLayout中的，出现这种情况有可能是IjkVideoView设置的宽高比和视频本身的宽高比不一样

**Comment by assion** [comment]
我视频宽高是根据我走自己写的图片微缩图高度宽度设置的，如果是这样情况，我是不是需要设置视频本身的宽高填充，请指点一下

**Comment by assion** [comment]
我现在是继承的IjkVideoView的一个视频控件，我是不是需要将这个视频控件的宽高填充满显示区域，还是说要将图片的宽高根据视频的本身宽高来设置一致

**Comment by assion** [comment]
变形也没关系，怎么填充能说一下吗，我填充了还是那样

**Comment by dueeeke** [comment]
设置SCREEN_SCALE_MATCH_PARENT
