### ISSUE TITLE
抖音Dome 怎么播放横向视频

### ISSUE THREAD

**Issue by a452894690** [dueeeke/DKVideoPlayer#172]
抖音Dome 播放横向视频的时候是竖向充满全屏的播放.这样导致了视频被拉伸的很严重.,怎么才能宽度充满高度自适应呢?

**Comment by dueeeke** [comment]
https://github.com/dueeeke/dkplayer/blob/master/app/src/main/java/com/dueeeke/dkplayer/activity/list/tiktok/TikTokActivity.java#L104
去掉这行试试

**Comment by a452894690** [comment]
好的. 晚上我回去再试试,
麻烦了
