### ISSUE TITLE
无缝衔接进入详情页自动播放

### ISSUE THREAD

**Issue by liweiGe** [dueeeke/DKVideoPlayer#174]
demo没有无缝进入详情自动播放的实例啊,问下这个框架能够实现吗

**Comment by dueeeke** [comment]
实现了，切到dev分支查看，看符不符合你需求，我是模仿哔哩哔哩动态页做的，欢迎提意见

**Comment by weikjblue** [comment]
能否实现 列表页无缝切换到详情页 自动播放，返回列表页继续进度播放 这里列表页为viewpager+fragment？
