### ISSUE TITLE
progress直接拉到最后会一直缓冲不能结束，拉到倒数第二秒都能正常结束。

### ISSUE THREAD

**Issue by marscl** [dueeeke/DKVideoPlayer#177]
demo也有这个问题。
测试地址：https://videos6.yijiaren888.com:777/2019/01/24/4Wz3IgFgblFCNG3r/playlist.m3u8

**Comment by dueeeke** [comment]
这个是ijkplayer的bug
唯一能做的就是seek 的时候postion减1。由于position的单位是毫秒，减1对进度影响不大，建议采用此方式
