### ISSUE TITLE
为啥关闭系统自动旋转，dkplayer依然能自动横屏播放

### ISSUE THREAD

**Issue by xilost** [dueeeke/DKVideoPlayer#186]
如题，应该跟着系统设置走才对。

**Comment by dueeeke** [comment]
1.跟着系统走体验并不好
2.controller中已经提供了锁定屏幕的方法
3.如想跟着系统走可在[此处](https://github.com/dueeeke/dkplayer/blob/master/dkplayer-java/src/main/java/com/dueeeke/videoplayer/player/BaseIjkVideoView.java#L85)加上如下代码：
            int rotation = Settings.System.getInt(getContext().getContentResolver(), Settings.System.ACCELEROMETER_ROTATION, 0);
            if (rotation == 0) return;
