### ISSUE TITLE
HTTP类型的实时流播放都是绿屏，rtsp类型的延时将近2秒左右

### ISSUE THREAD

**Issue by BeBroken** [dueeeke/DKVideoPlayer#188]
我播放http的流，整个画面都是绿屏了，还有好像rtsp的延时将近有2秒左右，请问下这个要怎么修改了？

**Comment by dueeeke** [comment]
是否开启硬解码，关闭试试
rtsp优化可参考[这里](https://www.jianshu.com/p/532d016d79e6)
