### ISSUE TITLE
请问怎么获取视频的总时长

### ISSUE THREAD

**Issue by AutumnLeavesss** [dueeeke/DKVideoPlayer#190]
获取播放进度以及视频的播放时长,以便用来实现历史播放这个功能,不知道该如何去操作呢?

**Comment by AutumnLeavesss** [comment]
SeekTo()这个方法没有用,getDuration()获取视频总时长也是为0.

**Comment by dueeeke** [comment]
总时长需要在视频已经prepared之后才能获取

**Comment by dhh940827** [comment]
> 总时长需要在视频已经prepared之后才能获取

我在demo里抖音那里的TikTokController 里setProgress()方法中写上
int position = (int) mMediaPlayer.getCurrentPosition();
        int duration = (int) mMediaPlayer.getDuration();
这两个为什么总是0呀，我看状态已经出现STATE_PREPARED了

**Comment by dueeeke** [comment]
@dhh940827 在STATE_PLAYING加上post(mShowProgress);，可参考StandardVideoController实现

**Comment by dhh940827** [comment]
谢谢，看了代码后找到问题了，不过这个post(mShowProgress)确实不显眼，还以为线程是自动调用的
