### ISSUE TITLE
退出全屏后fragment重新加载了视频不继续播放了

### ISSUE THREAD

**Issue by lorne666** [dueeeke/DKVideoPlayer#195]
退出全屏后fragment重新加载了，视频不继续播放了

**Comment by dueeeke** [comment]
在fragment所属的activity加入android:configChanges="keyboardHidden|orientation|screenSize"防止横竖屏屏切换重走生命周期

**Comment by lorne666** [comment]
加上这个，退出全屏就竖直方向播放了，我这个是一个fragment嵌套了2个子fragment,左侧的子fragment点击后右边的子fragment播放视频，全屏后就退回不到初始的页面，还是在播放页面，只不过是小屏显示了

**Comment by dueeeke** [comment]
没明白，初始页面是啥效果

**Comment by lorne666** [comment]
本来的页面是左边fragment是一个播放的列表，右边的是播放页面，现在点退出全屏还是在全屏播放页面，只是小屏显示了，本来的2个fragment显示不出来

**Comment by dueeeke** [comment]
点击控制器上的返回按钮正常吗

**Comment by lorne666** [comment]
点返回按钮还在播放页面，变成竖向小屏播放了，没有退出去

**Comment by dueeeke** [comment]
控制器你是用什么context创建的，是activity context吗

**Comment by dueeeke** [comment]
全屏和退出全屏是会依赖controller所属的activity的，你可以看看源码。在stopFullscreen那里断点调试

**Comment by lorne666** [comment]
控制器用的getActivity

**Comment by dueeeke** [comment]
嗯，断点stopFullscreen，看看有没有正常走退出全屏的逻辑

**Comment by lorne666** [comment]
doStartStopFullScreen方法mMediaPlayer.isFullScreen() 一直是false 执行的mMediaPlayer.startFullScreen()这个方法，退不出去

**Comment by dueeeke** [comment]
你是不是修改或者重写过startFullScreen和stopFullScreen方法

**Comment by lorne666** [comment]
重写了doStartStopFullScreen，都设置的横屏SCREEN_ORIENTATION_LANDSCAPE，因为返回后是竖屏的，其余都没改动过

**Comment by dueeeke** [comment]
你是要实现什么样的功能呢，为什么要重写此方法，按照正常的需求来说不需要去修改此方法

**Comment by lorne666** [comment]
因为我这是PAD版本需要横屏显示的

**Comment by dueeeke** [comment]
你的pad默认就是横屏是吧，如果是这样全屏和退出全屏根本不用去旋转屏幕，直接去除屏幕旋转的方法就行

**Comment by lorne666** [comment]
是的，默认横屏的，那还是得重写 doStartStopFullScreen ？

**Comment by dueeeke** [comment]
对的

**Comment by lorne666** [comment]
去掉旋转的代码，点返回按钮还是执行的startFullScreen这个方法，退不出去

**Comment by dueeeke** [comment]
断点一下startFullScreen方法，看看是否执行正常，我是通过mIsFullScreen 这个变量来记录是否处于全屏状态的

**Comment by lorne666** [comment]
全屏startFullScreen正常执行，点击返回按钮执行了onBackPressed中的stopFullScreen，然后执行doStartStopFullScreen 中的startFullScreen，  startFullScreen和stopFullScreen两个方法代码都执行了

**Comment by dueeeke** [comment]
你录个视频发我邮箱xinyunjian1995@gmail.com，我都整懵逼了😂

**Comment by lorne666** [comment]
好的
