### ISSUE TITLE
recycler无缝回退后点击事件消失

### ISSUE THREAD

**Issue by netdolphin** [dueeeke/DKVideoPlayer#202]
我在recyclerview中点击item后移除mIjkVideoView，无缝切换到新的activity，新生成controller，加入原来的mIjkVideoView。返回也是类似操作，重新加入到item的view中，都很正常。但是返回后原来的recyclerview上item点击事情不能触发了，controller到是可以

**Comment by shuanglong520** [comment]
@netdolphin @Doikki 这个问题解决没，我也遇到了，列表添加点击事件后，无缝播放返回，点击事件无效了，这应该怎么处理
