### ISSUE TITLE
升级2.5.5，编译报错

### ISSUE THREAD

**Issue by gh-txgdr** [dueeeke/DKVideoPlayer#206]
Error:Execution failed for task ':app:transformClassesWithMultidexlistForRelease'.
> java.io.IOException: Can't write 
multi-dex\release\componentClasses.jar] (Can't read 
intermediates\transforms\desugar\release\87.jar(;;;;;;**.class)] (Duplicate zip entry [87.jar:android/support/design/widget/CoordinatorLayout$Behavior.class]))

**Comment by dueeeke** [comment]
clear一下

**Comment by gh-txgdr** [comment]
clean 后再Rebuild 还是不行

**Comment by dueeeke** [comment]
初步断定是support library冲突，等下我发布一个新版你测试一下

**Comment by dueeeke** [comment]
这样吧，你去百度support library冲突，网上有很多解决方法，jitpack现在不给力，发布不了新版

**Comment by gh-txgdr** [comment]
不知道是不是我的as环境有问题

**Comment by dueeeke** [comment]
通过library方式引入正常吗

**Comment by gh-txgdr** [comment]
新建项目是正常的，导入是正常的

**Comment by dueeeke** [comment]
试一下2.5.6版，我已经发布到了jcenter，已经解决support library冲突，jitpack下个版本就弃用了，问题太多
