### ISSUE TITLE
开启缓存后，拖动进度条，已缓存的进度就不见了

### ISSUE THREAD

**Issue by hlgcgrass** [dueeeke/DKVideoPlayer#208]
比如已经缓存了50%，我就把进度条往后拖到30%，这时是能快速播放的，但是缓存的进度又退回到30%了，这个要怎么办呢

**Comment by 572705296** [comment]
我也是这个问题，emm，缓存的不应该能直接播放吗，还有GSYVideoPlayer项目的//exo缓存模式，支持m3u8，只支持exo
CacheFactory.setCacheManager(ExoPlayerCacheManager.class);作者能集成进去吗，

**Comment by dary123** [comment]
> 我也是这个问题，emm，缓存的不应该能直接播放吗，还有GSYVideoPlayer项目的//exo缓存模式，支持m3u8，只支持exo
> CacheFactory.setCacheManager(ExoPlayerCacheManager.class);作者能集成进去吗，

同问
