### ISSUE TITLE
播放的时候  会偶尔报错

### ISSUE THREAD

**Issue by ParkSouth** [dueeeke/DKVideoPlayer#212]
1 java.util.ArrayList$Itr.next(ArrayList.java:860)
--
2 com.dueeeke.videoplayer.player.IjkVideoView.setPlayState(IjkVideoView.java:111)
3 com.dueeeke.videoplayer.player.BaseIjkVideoView.onCompletion(BaseIjkVideoView.java:450)
4 com.dueeeke.videoplayer.player.IjkPlayer$3.onCompletion(IjkPlayer.java:270)
5 tv.danmaku.ijk.media.player.AbstractMediaPlayer.notifyOnCompletion(AbstractMediaPlayer.java:85)
6 tv.danmaku.ijk.media.player.IjkMediaPlayer$EventHandler.handleMessage(IjkMediaPlayer.java:985)
7 android.os.Handler.dispatchMessage(Handler.java:106)
8 android.os.Looper.loop(Looper.java:214)
9 android.app.ActivityThread.main(ActivityThread.java:7045)
10 java.lang.reflect.Method.invoke(Native Method)
11 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by dueeeke** [comment]
不要在播放结束后重新设置播放状态监听

**Comment by ParkSouth** [comment]
@dueeeke 好
