### ISSUE TITLE
调用seekTo()设置播放位置有问题

### ISSUE THREAD

**Issue by Lsier** [dueeeke/DKVideoPlayer#214]
ijkplayer调用seekTo(long time) ，并没有播放到预期的time节点，而是会回滚到time 节点之前左右的节点。

**Comment by dueeeke** [comment]
开启精准seek试试
            ijkVideoView.setCustomMediaPlayer(new IjkPlayer(context) {
                @Override
                public void setOptions() {
                    //精准seek
                    mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
                }
            });

**Comment by Lsier** [comment]
可以    谢谢
