### ISSUE TITLE
StandardVideoController 下出错

### ISSUE THREAD

**Issue by oake33** [dueeeke/DKVideoPlayer#216]
java.lang.NoSuchFieldError: No static field status_btn of type I in class Lcom/dueeeke/videoplayer/R$id; or its superclasses

**Comment by dueeeke** [comment]
status_btn 实在dkplayer-java中的，你有引入吗

**Comment by oake33** [comment]
implementation 'com.github.dueeeke.dkplayer:dkplayer-java:2.5.5'  我是按照这种方式引用的  ，是不要以工程的方式作为依赖
