### ISSUE TITLE
大神你好,我现在使用你这个播放器 播放公司的摄像头,出现了没有声音的情况

### ISSUE THREAD

**Issue by ZhiHaoZhong** [dueeeke/DKVideoPlayer#220]
我试过把so库换了8.3的,然后库也换了0.8.3的 这个问题就解决了!不知道是不是你的0.8.8so库有问题,还是ijk的问题了, 我使用的是RTSP播放留 rtsp:URL.sdp  这个地址,我直接用你的demo也是不行的,如果你需要测试 我可以提供地址给你!  毕竟我也想用最新的库.  联系我QQ295441346!  麻烦你了

**Comment by dueeeke** [comment]
地址发我邮箱

**Comment by ZhiHaoZhong** [comment]
每次都会变了 那个地址!你要看只能加我qq  你要看我就发给你!

**Comment by wjj201411** [comment]
同问，也是没有声音

**Comment by dueeeke** [comment]
@wjj201411 给个地址

**Comment by wjj201411** [comment]
这个要连着硬件，我可以给个.mov视频到您这边，播放本地mov格式的也没有声音
