### ISSUE TITLE
无法播放rtmp/rtsp直播推流

### ISSUE THREAD

**Issue by newcboy** [dueeeke/DKVideoPlayer#221]

**Comment by dueeeke** [comment]
能给个地址吗

**Comment by newcboy** [comment]
rtmp://live.hkstv.hk.lxdns.com/live/hks
rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov
麻烦看一下

**Comment by mingzaizai** [comment]
问下 播放rtmp的直播流解决了吗？dkplayer是支持rtmp的吧

**Comment by newcboy** [comment]
> 问下 播放rtmp的直播流解决了吗？dkplayer是支持rtmp的吧

可以直播了，是我们的视频源出了问题

**Comment by mingzaizai** [comment]
> > 问下 播放rtmp的直播流解决了吗？dkplayer是支持rtmp的吧
> 
> 可以直播了，是我们的视频源出了问题

好的 ，谢谢
