### ISSUE TITLE
RecyclerView播放问题

### ISSUE THREAD

**Issue by booldplx** [dueeeke/DKVideoPlayer#222]
RecyclerView播放视频,为什么IjkVideoView的父布局必须是LinearLayout,之前我用RelativeLayout就报错了

**Comment by dueeeke** [comment]
报什么错

**Comment by booldplx** [comment]
LinearLayout的布局管理器不能转化为RelativeLayout的布局管理器

**Comment by booldplx** [comment]
还有一个问题,视频item的播放按钮不居中是什么情况,那个播放图标偏右边一些
