### ISSUE TITLE
全屏播放时，按系统音量键会退出全屏。

### ISSUE THREAD

**Issue by newcboy** [dueeeke/DKVideoPlayer#224]

**Comment by dueeeke** [comment]
你是开启了自动全屏吧

**Comment by newcboy** [comment]
没有，都是正常的点击全屏按钮全屏。不过我的videoplayer是fragment中加载的

**Comment by newcboy** [comment]
我写了几个demo验证了一下，确实是在fragment中加载IjkVideoView，会出现点击系统音量键，退出全屏的情况。

**Comment by newcboy** [comment]
Sorry,是我们的框架出了问题，已经解决了。
