### ISSUE TITLE
视频列表点击全屏无反应

### ISSUE THREAD

**Issue by 15114846648** [dueeeke/DKVideoPlayer#240]

**Comment by liweiGe** [comment]
我替楼主回答了吧
两个可能性,一个是你设置了activity 的透明主题(侧滑返回),另外可能就是清单文件没有配置
![image](https://user-images.githubusercontent.com/25901728/57439226-23932a80-7278-11e9-92c3-460fd60f17f8.png)

**Comment by 15114846648** [comment]
这个我也设置了




------------------ 原始邮件 ------------------
发件人: "liweiGe"<notifications@github.com>; 
发送时间: 2019年5月9日(星期四) 下午4:33
收件人: "dueeeke/dkplayer"<dkplayer@noreply.github.com>; 
抄送: "淺唱、我有罪"<755454978@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dueeeke/dkplayer] 视频列表点击全屏无反应 (#240)




我替楼主回答了吧
 两个可能性,一个是你设置了activity 的透明主题(侧滑返回),另外可能就是清单文件没有配置

**Comment by dueeeke** [comment]
@15114846648 给你回邮件了，不能使用application context创建控制器

**Comment by 15114846648** [comment]
你好，麻烦问一下，视频播放器的那个开始按钮我怎么更换一下图标
------------------ 原始邮件 ------------------
发件人: "liweiGe"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午4:33
收件人: "dueeeke/dkplayer"<dkplayer@noreply.github.com>;
抄送: "淺唱、我有罪"<755454978@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dueeeke/dkplayer] 视频列表点击全屏无反应 (#240)




我替楼主回答了吧
 两个可能性,一个是你设置了activity 的透明主题(侧滑返回),另外可能就是清单文件没有配置

**Comment by JohnDwang** [comment]
我也遇到了同样的问题
