### ISSUE TITLE
您好，请问如何才能实现记录播放位置，以便于下次播放

### ISSUE THREAD

**Issue by GFL0614** [dueeeke/DKVideoPlayer#244]
您好，请问如何才能实现记录播放位置，以便于下次播放

**Comment by dueeeke** [comment]
setProgressManager，看我demo,我有演示

**Comment by GFL0614** [comment]
谢谢您

**Comment by GFL0614** [comment]
> setProgressManager，看我的演示，我有演示

谢谢您

**Comment by marscl** [comment]
> setProgressManager，看我demo,我有演示

请问在demo那里。没有找到
