### ISSUE TITLE
demo中的分段视频concat失效

### ISSUE THREAD

**Issue by perfect-network** [dueeeke/DKVideoPlayer#247]
http://pl.feixiong.tv/Admin/Service/plconcat?url=http%3A%2F%2Fv.youku.com%2Fv_show%2Fid_XMjg4ODUzMDQyNA%3D%3D.html&source_id=1&sel_type=FLV&stream_type=SD

打不开？？

**Comment by dueeeke** [comment]
试试这个http://155.138.214.164/test/test.ffconcat

**Comment by perfect-network** [comment]
> 试试这个http://155.138.214.164/test/test.ffconcat
不是做android的编译不成功。。我想改个URL都不行
