### ISSUE TITLE
点播播放直播视频，滑动进度会卡住，怎么实现直播和点播都在一个播放器里，且直播滑动进度条可以设置不反应

### ISSUE THREAD

**Issue by thispays** [dueeeke/DKVideoPlayer#261]
点播播放直播视频，滑动进度会卡住，怎么实现直播和点播都在一个播放器里，且直播滑动进度条可以设置不反应

**Comment by dueeeke** [comment]
看我demo, 控制器的setlive方法，或者监听视频总时长，根据总时长改变ui，一般来说直播都是获取不到总时长的，如果返回值是0就可以认为是直播

**Comment by thispays** [comment]
> 看我demo, 控制器的setlive方法，或者监听视频总时长，根据总时长改变ui，一般来说直播都是获取不到总时长的，如果返回值是0就可以认为是直播

if (intent != null) {
            StandardVideoController controller = new StandardVideoController(this);
            boolean isLive = intent.getBooleanExtra("isLive", false);
            if (isLive) {
                controller.setLive();
            }

是不是这句话，你的代码点播和直播就是这代码控制的吗？我设置了怎么不改变播放器，请指教。
