### ISSUE TITLE
Rtsp 3.0.0版本不能播放

### ISSUE THREAD

**Issue by leifu1107** [dueeeke/DKVideoPlayer#273]
Rtsp流 3.0.0版本不能播放 com.dueeeke.videoplayer.player.VideoView使用这个,改用2.5.5版本的 IjkVideoView可以播放,希望作者给予回复什么原因,还是我用错了什么

**Comment by dueeeke** [comment]
3.0.0之后默认使用系统mediaplayer进行解码，系统mediaplayer是不支持rtsp的，需切换成ijkplayer方可播放，具体方法看wiki

**Comment by dueeeke** [comment]
另外建议使用3.0.1，3.0.0有重大bug
