### ISSUE TITLE
3.0.1版本  Exo内核不能保存播放进度

### ISSUE THREAD

**Issue by GFL0614** [dueeeke/DKVideoPlayer#274]
3.0.1版本  Exo内核不能保存播放进度

**Comment by dueeeke** [comment]
给个地址

**Comment by GFL0614** [comment]
> 给个地址

你提供的api点播里  用Exo内核就不能保存进度  其他两个都没问题呀

**Comment by dueeeke** [comment]
3.0.2已修复

**Comment by GFL0614** [comment]
> 3.0.2已修复

非常感谢!!!      我能再弱弱的提个意见么  右边调节亮度 左边调节音量  被用户吐槽了很久了  大部分软件都是右边音量  左边亮度
