### ISSUE TITLE
Fragment嵌套多层的，播放器状态和全屏该怎么控制呢？

### ISSUE THREAD

**Issue by zaaach** [dueeeke/DKVideoPlayer#278]
公司项目结构是Activity+Fragment，有的Fragment里是ViewPager+Fragment，最里面一层有视频列表，这个时候播放器状态怎么控制？按demo监听fragment生命周期方法控制播放状态失效

**Comment by weikjblue** [comment]
同问 +1

**Comment by dueeeke** [comment]
监听fragment所属的activity的生命周期即可
