### ISSUE TITLE
重播问题

### ISSUE THREAD

**Issue by naiveking** [dueeeke/DKVideoPlayer#280]
竖屏的时候播放完点击重播一直loading；无法重新播放；另外问下，竖屏播放控制器能显示返回按钮吗？

**Comment by liweiGe** [comment]
我也有个重播问题想问问,就是每次点重播都是重新初始化视频控件,才会有loading的效果,这个该怎么解决,直接就是视频跟点播放一样没有loading的效果

**Comment by cgpllx** [comment]
竖屏toolbar 上面自己添加
