### ISSUE TITLE
抖音demo，在视频界面打开新界面，再回来时，视频比例会有变化，两边有黑边。

### ISSUE THREAD

**Issue by ntrer** [dueeeke/DKVideoPlayer#281]
滑动下一个视频，再回来又好了。我用的不是你这个最新的，用的是其他项目里引用的你的ijkplayer封装。我看你最新的抖音demo把ijk换了，不知是不是ijk的原因。
[https://s2.ax1x.com/2019/07/17/ZqD6gS.jpg](url)
[https://s2.ax1x.com/2019/07/17/ZqDRBj.jpg](url)

**Comment by dueeeke** [comment]
应该不是，我demo用的就是Ijk

**Comment by ntrer** [comment]
> 应该不是，我demo用的就是Ijk

这个我解决了，在播放界面resume的时候重新
 ijkVideoView.setScreenScale(IjkVideoView.SCREEN_SCALE_CENTER_CROP);
设置一下比例就没事了。

但是还有个新问题，就是先把视频暂停，然后跳新界面，再回来时，就黑屏了，视频没播放，也没暂停。切换一下视频才能恢复，这个怎么解决，我看抖音的是暂停跳新界面回来视频自动接着播放
