### ISSUE TITLE
m3u8 视频无法循环播放

### ISSUE THREAD

**Issue by helloxkk** [dueeeke/DKVideoPlayer#285]
播放m3u8的视频会有问题, 无法循环播放, 视频地址: http://vod2017.qiongliao.net/4db0b9c07dcb4403933ed406bb2d17ce/d919946ec6a041a1be08082cd178fbf1-4b6ffae84f2e1d243955ecaedcf11a3e.m3u8?auth_key=1563672278-0-0-81dd45a18fd267800491e15af4a36f50

**Comment by helloxkk** [comment]
我在代码中设置了循环播放, 但是播放结束时的状态是 `STATE_PLAYBACK_COMPLETED` , 导致无法继续播放?

在 本项目的 `Demo` 中播放 m3u8 视频则会无限循环卡死在 `STATE_BUFFERING`、`STATE_BUFFERED` 状态下.

**Comment by dueeeke** [comment]
这是ijkplayer的bug。推荐使用exoplayer去播放hls。exoplayer对hls的处理要比ijkplayer好很多

**Comment by helloxkk** [comment]
好的, 谢谢大佬
