### ISSUE TITLE
切换ExoMediaPlayerFactory

### ISSUE THREAD

**Issue by guoyin1227** [dueeeke/DKVideoPlayer#286]
切换为 ExoMediaPlayerFactory  好像不支持 SSL，如何设置

**Comment by dueeeke** [comment]
你是指不支持https？

**Comment by guoyin1227** [comment]
恩，ijk的可以播放https,exo的 就是加载失败

**Comment by guoyin1227** [comment]
设置https忽略证书 
参考        if (mSkipSSLChain) {
            GSYExoHttpDataSourceFactory dataSourceFactory = new GSYExoHttpDataSourceFactory(Util.getUserAgent(context,
                    TAG), preview ? null : new DefaultBandwidthMeter(), GSYExoHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                    GSYExoHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, allowCrossProtocolRedirects);
            if (mMapHeadData != null && mMapHeadData.size() > 0) {
                for (Map.Entry<String, String> header : mMapHeadData.entrySet()) {
                    dataSourceFactory.getDefaultRequestProperties().set(header.getKey(), header.getValue());
                }
            }
            return dataSourceFactory;
        }
