### ISSUE TITLE
demo中进度条问题

### ISSUE THREAD

**Issue by nwhhades** [dueeeke/DKVideoPlayer#288]
进度条拉到最后，自动回退几秒的功能是哪控制的 找了一下午都没看的这个功能的代码在哪，我自定义的VideoController并没有这样的效果
我想一种方案如下:
@Override
    public void onStopTrackingTouch(SeekBar seekBar) {
/// 这里
if(seekBar.getProgress() == 1000) {
         在这重新改变进度条
}
///
        long duration = mMediaPlayer.getDuration();
        long newPosition = (duration * seekBar.getProgress()) / mVideoProgress.getMax();
        mMediaPlayer.seekTo((int) newPosition);
        mIsDragging = false;
        post(mShowProgress);
        show();
    }

**Comment by dueeeke** [comment]
你可以提交一个pr

**Comment by nwhhades** [comment]
> 你可以提交一个PR

额，我的问题是 你写的demo中有这样的功能（进度条拉到最后，自动回退几秒的功能），但我却没找到相应的代码，能告诉一下在哪吗

**Comment by dueeeke** [comment]
这个不是功能

**Comment by dueeeke** [comment]
算ijk的bug，ijk seek不够精准

**Comment by nwhhades** [comment]
> 算ijk的bug，ijk seek不够精准

qaq,自闭了。我还找了一下午，断了n个断点，硬是没找到代码。    原来是bug啊。发现问题了   和你demo用的视频不同，换成你那个视频也回退了，谢谢大佬，播放器好用！赞👍
自定义的效果图：哈哈
![image](https://user-images.githubusercontent.com/31042987/61680243-72ab1080-ad3b-11e9-90d6-0fe7f5e4845b.png)

**Comment by GXSZone** [comment]
@nwhhades 你那个播放器选集的侧边栏的思路能说下吗
