### ISSUE TITLE
是否支持androidx 

### ISSUE THREAD

**Issue by yuzeGitHub** [dueeeke/DKVideoPlayer#289]

**Comment by dueeeke** [comment]
暂不支持

**Comment by yuzeGitHub** [comment]
您好，辛苦了，暂时不知道有没有适配Android x  的计划！

**Comment by yuzeGitHub** [comment]
辛苦了，暂时不知道有没有适配Android x 的计划！

**Comment by liweiGe** [comment]
> 辛苦了，暂时不知道有没有适配Android x 的计划！

我就是把项目下载下来自己修改成android X的,别想一行implementation 就完事了,自己动手吧
