### ISSUE TITLE
希望大佬能支持m3u8缓存。

### ISSUE THREAD

**Issue by ccflyy** [dueeeke/DKVideoPlayer#290]

**Comment by marscl** [comment]
https://github.com/CarGuo/GSYVideoPlayer

**Comment by marscl** [comment]
可以参考下https://github.com/CarGuo/GSYVideoPlayer

**Comment by caiyoufei** [comment]
https://github.com/caiyoufei/MyVideoView/blob/master/app/src/main/java/com/cc/dkvideo/dkplayer/MyExoMediaPlayer.kt
重写方法实现m3u8的边播边存

**Comment by nikolamakin** [comment]
> https://github.com/khaos116/MyVideoView/blob/master/app/src/main/java/com/cc/dkvideo/dkplayer/MyExoMediaPlayer.kt
> 重写方法实现m3u8的边播边存

404了，求重开
