### ISSUE TITLE
可否添加一个竖屏全屏的播放界面的DEMO

### ISSUE THREAD

**Issue by thispays** [dueeeke/DKVideoPlayer#292]
可否添加一个竖屏全屏的播放界面的DEMO，抖音那种没有控制界面

**Comment by dueeeke** [comment]
不好意思，请自行实现

**Comment by caiyoufei** [comment]
@thispays 自己动手改改吧
![image](https://user-images.githubusercontent.com/11989916/67916835-a19e1180-fbc9-11e9-9d4a-cd4df52810b3.png)

**Comment by caiyoufei** [comment]
@thispays 效果还可以，Gift在横竖屏切换的时候有点卡顿，真机上没那个异常UI
![演示效果](https://user-images.githubusercontent.com/11989916/67917868-ee371c00-fbcc-11e9-8f52-4231d9ab29a1.gif)
