### ISSUE TITLE
你好 这个有 切换清晰度的 方法吗

### ISSUE THREAD

**Issue by A451323699** [dueeeke/DKVideoPlayer#293]

**Comment by dueeeke** [comment]
看我demo

**Comment by A451323699** [comment]
有的，我是下载源码，用moudle,的方式引入的，不知道你是不是------------------ 原始邮件 ------------------
发件人: "dueeeke"<notifications@github.com>
发送时间: 2019年9月11日(星期三) 晚上6:51
收件人: "dueeeke/DKVideoPlayer"<DKVideoPlayer@noreply.github.com>;
抄送: "A451323699"<451323699@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dueeeke/DKVideoPlayer] 你好 这个有 切换清晰度的 方法吗 (#293)



Closed #293.
 
&mdash;
