### ISSUE TITLE
huawei nava 3 emui android 9.0  检测为病毒软件

### ISSUE THREAD

**Issue by ipetu** [dueeeke/DKVideoPlayer#296]
![微信图片_20190805001212](https://user-images.githubusercontent.com/5442932/62426325-de1ab800-b715-11e9-94da-4af142d51978.jpg)
![微信图片_20190805001217](https://user-images.githubusercontent.com/5442932/62426326-df4be500-b715-11e9-858a-1ada4532cbf8.jpg)

**Comment by dueeeke** [comment]
不是病毒应用。。。。应该是误报

**Comment by yangdengxueshi** [comment]
Demo华为报病毒  注释掉所有 signingConfig 可解决
