### ISSUE TITLE
请问recyclerview 列表里面，如何增加视频预加载，点击跳转详情页时可以直接

### ISSUE THREAD

**Issue by zhuoshirong** [dueeeke/DKVideoPlayer#298]
请问视频如何增预加载功能，比如头条小视频，滚动到下个视频时，可以直接播放，不用等待类似的做法。

**Comment by dueeeke** [comment]
暂时无法实现，不过头条也没有实现你说的预加载功能，只是他们的网络优化的比较好，能实现秒开罢了
