### ISSUE TITLE
一直转圈圈 加载中

### ISSUE THREAD

**Issue by BarkSheep** [dueeeke/DKVideoPlayer#301]
我按照教程配置之后  点击播放按钮后一直加载中 过一会提示加载失败  试了很多次

**Comment by dueeeke** [comment]
给个地址

**Comment by BarkSheep** [comment]
mVideoView.setUrl("http://vfx.mtime.cn/Video/2019/02/04/mp4/190204084208765161.mp4");
        StandardVideoController controller = new StandardVideoController(getContext());
        controller.setTitle("213");
        mVideoView.setVideoController(controller);
//        //保存播放进度
//        mVideoView.setProgressManager(new ProgressManagerImpl());
//        //播放状态监听
//        mVideoView.addOnVideoViewStateChangeListener(mOnVideoViewStateChangeListener);
        mVideoView.start();

我保证按照文档和demo进行了配置  可就是加载不出来视频

**Comment by dueeeke** [comment]
你换成ijk或者exo试试

**Comment by BarkSheep** [comment]
感谢  使用IjkPlayer解码可以播放了   但是为什么我下载demo可以默认使用系统的MediaPlayer进行解码进行播放  很好奇

**Comment by dueeeke** [comment]
有报什么错吗

**Comment by BarkSheep** [comment]
并没有

**Comment by dueeeke** [comment]
播放器是进入STATE_ERROR状态了吗，可以试着在VideoView setPlayState那里断个点，看看一下调用栈，看看是怎么引起的

**Comment by BarkSheep** [comment]
好的  我找找

**Comment by dueeeke** [comment]
还有一种可能，你把地址的http换成https试试

**Comment by BarkSheep** [comment]
果然  把http换成https就可以正常播放了  好神奇

**Comment by dueeeke** [comment]
你的系统是Android P?

**Comment by BarkSheep** [comment]
对 小米9

**Comment by dueeeke** [comment]
Android P已经默认不允许明文传输数据，也就是不支持http，我demo是做了处理，我在清单文件的application节点中配置了usesCleartextTraffic=true

**Comment by BarkSheep** [comment]
抱歉 忘了这茬了  我针对公司服务器域名配置了cleartextTrafficPermitted = true  没有配置usesCleartextTraffic   而且我用的视频链接是随便从网上找的  并不在公司服务器里
