### ISSUE TITLE
获取视频宽高

### ISSUE THREAD

**Issue by 18819318753** [dueeeke/DKVideoPlayer#302]
你好，如果列表的视频宽高，我想按照实际视频比例，展示，有没有办法获取呢？

**Comment by 18819318753** [comment]
我用的getVideoSize这个获取的宽高都是0,，麻烦指导一下。

**Comment by dueeeke** [comment]
你是想在视频播放之前拿到宽高？

**Comment by 18819318753** [comment]
是的，想在播放钱，拿到

**Comment by dueeeke** [comment]
那只能叫你们后台在视频入库的时候记录一下宽高，然后在接口中返回

**Comment by 18819318753** [comment]
好的，明白，谢谢了

**Comment by ldxyzhou** [comment]
如果视频宽度是800 屏幕宽度是1280 怎么填充满？
