### ISSUE TITLE
播放视频 会出现播放一会 播放出错的问题情况

### ISSUE THREAD

**Issue by A451323699** [dueeeke/DKVideoPlayer#303]
tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f3954e730)
IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f3954f4c0)
IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f3954f8b0)
IJKMEDIA: SDL_JNI_ThreadDestroyed: [11026] didn't call SDL_JNI_DetachThreadEnv() explicity
这是打印 出来的信息 这个是因为什么呢，无从下手

**Comment by dueeeke** [comment]
换exo试试

**Comment by A451323699** [comment]
嗯，好的 我试试

**Comment by A451323699** [comment]
换成exo 的核心播放 没有这个问题了  谢谢你的解答
