### ISSUE TITLE
播放阿里云上的视频地址

### ISSUE THREAD

**Issue by Jay-YaoJie** [dueeeke/DKVideoPlayer#306]
danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by Jay-YaoJie** [comment]
阿里云地址播放不出来

http://lbtafx.oss-cn-shenzhen.aliyuncs.com/video/mp4/4dd16201908201006425975.mp4

danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by Jay-YaoJie** [comment]
![image](https://user-images.githubusercontent.com/18596432/63318531-5950b080-c349-11e9-91e2-71ec68471031.png)

**Comment by Jay-YaoJie** [comment]
//        VideoViewManager.setConfig(
//            VideoViewConfig.newBuilder()
//            //使用使用IjkPlayer解码
//            .setPlayerFactory(IjkPlayerFactory.create(this))
//            //使用ExoPlayer解码
//            .setPlayerFactory(ExoMediaPlayerFactory.create(this))
//            //使用MediaPlayer解码
//            .setPlayerFactory(AndroidMediaPlayerFactory.create(this))
//            .build());

这三个我每一个都试过了，都不行
![image](https://user-images.githubusercontent.com/18596432/63318671-d8de7f80-c349-11e9-8b41-27ebe7445884.png)

**Comment by dueeeke** [comment]
你这视频访问不了

**Comment by Jay-YaoJie** [comment]
https://lbtafx.oss-cn-shenzhen.aliyuncs.com/video/mp4/db14d201908231421197737.mp4
