### ISSUE TITLE
SCREEN_SCALE_ORIGINAL无效

### ISSUE THREAD

**Issue by luqiao19950804** [dueeeke/DKVideoPlayer#307]
在播放播放4:3的视频的时候
默认是使用16:9在播放
设置SCREEN_SCALE_ORIGINAL自适应，无效
设置SCREEN_SCALE_4_3可用，但是16:9的视频也会出问题

**Comment by dueeeke** [comment]
SCREEN_SCALE_ORIGINAL是按视频的原始分辨率显示

**Comment by luqiao19950804** [comment]
好的，我这边发现问题了，是视频本身属性的原因造成的，播放器正常播放比例是4:3，但是视频属性里面分辨率确实1024:512，应该正常情况下是没有问题的，谢了，老哥
