### ISSUE TITLE
关于seekto的问题

### ISSUE THREAD

**Issue by dhh940827** [dueeeke/DKVideoPlayer#308]
1、在前3秒（？）左右拖拉进度条后，视频会自动从0秒播放。在短视频上拖拉特别明显。
2、好像进度条拖拉都是这样的，拖到一定时间例，如0：55，一般都会从（52 - 54）秒处开始，不是很准确，这是什么问题呢。

**Comment by dueeeke** [comment]
使用exoplayer或者#214
