### ISSUE TITLE
播放完毕后，点击重新播放一直转圈圈（系统默认的解码器有这个问题，其他两个没这问题，安装您的demo也一样）

### ISSUE THREAD

**Issue by qzyailch** [dueeeke/DKVideoPlayer#311]
![Screenshot_2019-08-26-17-53-31-364_com dueeeke dk](https://user-images.githubusercontent.com/13062686/63682563-cc1ac980-c82a-11e9-86cc-7461869fb448.png)
![Screenshot_2019-08-26-17-54-15-345_com dueeeke dk](https://user-images.githubusercontent.com/13062686/63682571-cf15ba00-c82a-11e9-88dd-2b3679887532.png)

**Comment by 15281046619** [comment]
我也是这个问题，请问解决了嘛？

**Comment by dueeeke** [comment]
3.0.3已经修复
