### ISSUE TITLE
D8编译错误

### ISSUE THREAD

**Issue by Joslyn-Chen** [dueeeke/DKVideoPlayer#316]
`Caused by: com.android.tools.r8.utils.AbortException: Error: Default method desugaring of `com.dueeeke.videoplayer.exo.ExoMediaPlayer` failed because its super class `com.dueeeke.videoplayer.player.AbstractPlayer` is missing
	at com.android.tools.r8.utils.Reporter.a(:21)
	at com.android.tools.r8.utils.Reporter.a(:7)
	at com.android.tools.r8.utils.t.a(:36)
	... 94 more`

**Comment by dueeeke** [comment]
你是使用源码引入吗，如果是的话应该要把gradle中的compileOnly改为api

**Comment by Joslyn-Chen** [comment]
java8使用了的，引入都是用的api。运行没问题，就是打包会出这个错

**Comment by aprz512** [comment]
低版本 agp 的 r8 似乎有bug，指定最新版本的就好了
