### ISSUE TITLE
关于4k视频播放缓慢卡帧的问题。

### ISSUE THREAD

**Issue by songjiejoy** [dueeeke/DKVideoPlayer#321]
问题描述：4K视频播放变成慢动作，播放速度是正常的20%，例如一个7秒长的视频，播放完成需要35秒时间，而且视频控件底下的计时也会变成  00:35/00:7  这种分子比分母大的情况。

尝试解决 ： 1. 在application全局加入.setEnableMediaCodec(true)，无法解决
                     2.在局部加入.setEnableMediaCodec(true) ，无法解决
                     3.按照您#152的建议，加入
.setCustomMediaPlayer(new IjkPlayer(this) {
@override
public void setEnableMediaCodec(boolean isEnable) {
super.setEnableMediaCodec(isEnable);
int value = isEnable ? 1 : 0;
mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-hevc", value);
}
})
还是无法解决。请问应该如何优化呢？（ijkplayer核心）

**Comment by dueeeke** [comment]
给个地址

**Comment by songjiejoy** [comment]
2个4K视频的测试地址都发您邮箱了，一个7秒 一个8秒，您看一下。

**Comment by dueeeke** [comment]
没收到

**Comment by songjiejoy** [comment]
发到您这个邮箱了 xinyunjian1995@gmail.com，由于视频地址带IP，您是否方便加下我QQ 316160024发您，验证随便填写。

**Comment by dueeeke** [comment]
加你了

**Comment by songjiejoy** [comment]
多谢作者，问题已解决，解决方法：
mVideoView.setPlayerFactory(new PlayerFactory() {
                @Override
                public AbstractPlayer createPlayer() {
                    return new IjkPlayer(PlayerActivity.this) {

                        @Override
                        public void setEnableMediaCodec(boolean isEnable) {
                            super.setEnableMediaCodec(isEnable);
                            int value = isEnable ? 1 : 0;
                            mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-hevc", value);
                        }
                    };
                }
            });
            mVideoView.setEnableMediaCodec(true);
