### ISSUE TITLE
在播放核心为MediaPlayer时，点击重新播放，会一直loading

### ISSUE THREAD

**Issue by TianDehua** [dueeeke/DKVideoPlayer#329]
log信息
09-10 13:59:37.411 15949-15949/com.dueeeke.dkplayer I/MediaPlayer: [HSM] stayAwake false uid: 10088, pid: 15949
09-10 13:59:37.414 15949-15966/com.dueeeke.dkplayer E/BufferQueueProducer: [SurfaceTexture-0-15949-16] dequeueBuffer: BufferQueue has been abandoned
09-10 13:59:37.423 15949-15960/com.dueeeke.dkplayer E/BufferQueueProducer: [SurfaceTexture-0-15949-16] cancelBuffer: BufferQueue has been abandoned
09-10 13:59:37.439 15949-15966/com.dueeeke.dkplayer E/BufferQueueProducer: [SurfaceTexture-0-15949-16] connect(P): BufferQueue has been abandoned
09-10 13:59:37.448 15949-15949/com.dueeeke.dkplayer W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: http://book.ellabook.cn/B201710250666.mp4
09-10 13:59:37.448 15949-15949/com.dueeeke.dkplayer I/MediaPlayer: setDataSource(http://book.ellabook.cn/B201710250666.mp4)
09-10 13:59:37.451 15949-15949/com.dueeeke.dkplayer E/BufferQueueProducer: [SurfaceTexture-0-15949-16] connect(P): BufferQueue has been abandoned
09-10 13:59:37.453 15949-15949/com.dueeeke.dkplayer E/DKPlayer: STATE_ERROR
09-10 13:59:37.453 15949-15949/com.dueeeke.dkplayer E/DKPlayer: STATE_PREPARING
09-10 13:59:37.454 15949-15949/com.dueeeke.dkplayer E/DKPlayer: PLAYER_NORMAL

**Comment by dueeeke** [comment]
你用的什么版本

**Comment by TianDehua** [comment]
> 你用的什么版本

3.0.2

**Comment by dueeeke** [comment]
用3.0.3

**Comment by TianDehua** [comment]
> 用3.0.3

这个版本是可以的，辛苦
