### ISSUE TITLE
在gradle 中加ijk的库一直报错

### ISSUE THREAD

**Issue by hyr0318** [dueeeke/DKVideoPlayer#331]
![1568455723910](https://user-images.githubusercontent.com/15108892/64906562-c540f180-d71a-11e9-9448-176930fa80ec.jpg)
![1568455697895](https://user-images.githubusercontent.com/15108892/64906564-cc67ff80-d71a-11e9-802e-5c127e7b9732.jpg)

**Comment by dueeeke** [comment]
应该是你当前的网络环境连接不上jcenter
