### ISSUE TITLE
视频画面暂停

### ISSUE THREAD

**Issue by JokerCats** [dueeeke/DKVideoPlayer#333]
点击菜单键进入进程菜单，再次点击DKPlayer，视频继续播放（可以听到声音）但画面卡住。
复现位置：列表播放 --> 抖音。

**Comment by dueeeke** [comment]
什么手机，以及系统版本

**Comment by JokerCats** [comment]
> 什么手机，以及系统版本

您好 我测试机是OPPO R9m & Android API 22

**Comment by dueeeke** [comment]
#72
