### ISSUE TITLE
D8编译器错误

### ISSUE THREAD

**Issue by shichuanenhui** [dueeeke/DKVideoPlayer#335]
Default method desugaring of `com.dueeeke.videoplayer.exo.ExoMediaPlayer` failed because its super class `com.dueeeke.videoplayer.player.AbstractPlayer` is missing

使用了    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8 targetCompatibility JavaVersion.VERSION_1_8 }
也是这个错误,怎么解决

**Comment by Mingyueyixi** [comment]
哥，大概率是你的编译插件太低了，com.android.tools.build:gradle弄到4，就好了。因为老版本默认的 r8 插件无法处理default method，你也可以试试指定新的 r8 插件
