### ISSUE TITLE
ijkplayer ANR问题

### ISSUE THREAD

**Issue by liweiGe** [dueeeke/DKVideoPlayer#344]
anr 的问题概率还很高
![image](https://user-images.githubusercontent.com/25901728/65653263-289a2000-e047-11e9-99c2-331b366b3297.png)
![image](https://user-images.githubusercontent.com/25901728/65653288-39e32c80-e047-11e9-9232-34cfb2976a90.png)

**Comment by dueeeke** [comment]
请升级版本

**Comment by liweiGe** [comment]
![image](https://user-images.githubusercontent.com/25901728/65668006-7fb5ea00-e073-11e9-96a9-07780cbc4841.png)
就这一处改动吧,没其他了吧?

**Comment by dueeeke** [comment]
没了
