### ISSUE TITLE
重播问题

### ISSUE THREAD

**Issue by pz-bottle** [dueeeke/DKVideoPlayer#345]
核心使用MediaPlayer ，点击重播有反应但是一直在加载，播不了

**Comment by dueeeke** [comment]
你用的什么版本

**Comment by pz-bottle** [comment]
我是下载demo发现的，我运行demo，将核心播放器切换为MediaPlayer，然后播放事例视频，播放完后点重播就一直处于加载状态播不了，其他两个核心播放器没有这个问题

**Comment by dueeeke** [comment]
看一下MediaPlayer的日志

**Comment by pz-bottle** [comment]
> 看一下MediaPlayer的日志

Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: https://boxue-resource.oss-cn-shenzhen.aliyuncs.com/tie/video/2019073111225695139.mp4

**Comment by pz-bottle** [comment]
> 看一下MediaPlayer的日志

点击相应事件是mMediaPlayer.replay(true);这个

**Comment by dueeeke** [comment]
我自己测试不存在此问题，建议不要使用系统的mediaplayer，兼容性很差，我推荐ExoPlayer
