### ISSUE TITLE
如何再抖音里监听播放失败，然后从新加载一次播放链接

### ISSUE THREAD

**Issue by cuikun121** [dueeeke/DKVideoPlayer#347]

**Comment by cuikun121** [comment]
请回复

**Comment by cuikun121** [comment]
谢谢

**Comment by dueeeke** [comment]
Controller中重写setPlayState或者对VideoView设置OnVideoViewStateChangeListener

**Comment by lushu4** [comment]
> Controller中重写setPlayState或者对VideoView设置OnVideoViewStateChangeListener

具体代码呢，老哥
