### ISSUE TITLE
在列表使用时复用view新建controller问题

### ISSUE THREAD

**Issue by chinamingsss** [dueeeke/DKVideoPlayer#349]
StandardVideoController controller = new StandardVideoController(helper.itemView.getContext());
VideoView mVideoView = helper.getView(R.id.video_player);

每次都new一个controller会发现列表滑动不流畅有卡顿，是不是可以复用？不要每次都new

**Comment by dueeeke** [comment]
可以复用

**Comment by 183883324** [comment]
> 标准视频控制器=新StandardVideoController(helper.itemView.getContext())；
> VideoView mVideoView=helper.getView(R.id.视频_Player)；
> 
> 每次都新一个控制器会发现列表滑动不流畅有卡顿，是不是可以复用？不要每次都新

请问你是怎么复用的 我也会造成卡顿

**Comment by 183883324** [comment]
@chinamingsss   请问你是怎么复用的  我也会造成卡顿

**Comment by chinamingsss** [comment]
请问如何复用啊？复用得话会不会造成来回滑动view状态出现问题

**Comment by chinamingsss** [comment]
@183883324 我现在是按照作者写得那种方式做得，每次都是new，但是我感觉每次new会渲染新得布局就会卡顿，复用还没研究

**Comment by 183883324** [comment]
@chinamingsss   我也是 抖音那个复用的好像也会出现卡顿     我是一个activit两个frgament各放抖音和列表播放  刚开始加载进去真的很卡。  后面复用也会造成卡顿。

**Comment by chinamingsss** [comment]
@183883324 复用也会卡顿吗？你用得什么控件是recycleview吗

**Comment by chinamingsss** [comment]
@183883324 加我qq咱们聊 289467139

**Comment by dueeeke** [comment]
@chinamingsss @183883324 我不太理解二位的意思，现在我把控制的创建放在viewholder中就是为了复用啊
