### ISSUE TITLE
怎样实现同时缓存多个视频,实现抖音那样的切换瞬间播放

### ISSUE THREAD

**Issue by inshyma** [dueeeke/DKVideoPlayer#355]
如题

**Comment by dueeeke** [comment]
切到Dev分支查看，你说的功能已经实现，还在测试阶段

**Comment by inshyma** [comment]
大佬  你是想用ViewPager的预加载么...

**Comment by dueeeke** [comment]
你有更好的方法吗

**Comment by inshyma** [comment]
aliyun的sdk中 有个[AliListPlayer](http://alisdk-api-doc.oss-cn-hangzhou.aliyuncs.com/player/4.6.0/android/com/aliyun/player/AliListPlayer.html) 不可以通过url预加载视频么?
