### ISSUE TITLE
这个播放器怎么播放本地视频文件呢？

### ISSUE THREAD

**Issue by jiancheng2018** [dueeeke/DKVideoPlayer#356]
有哪位好心的兄弟回答下我的问题

**Comment by NSocket** [comment]
好像是支持本地播放的，看看你手机存储权限有没有开，不能的话可以使用NanoHTTPD搭建一个本地服务器来播放本地视频

**Comment by dueeeke** [comment]
setUrl("file://你的视频绝对路径");就行了，注意访问权限
