### ISSUE TITLE
如何获取在线播放地址视频文件的存储大小？

### ISSUE THREAD

**Issue by MIkeeJY** [dueeeke/DKVideoPlayer#357]

**Comment by dueeeke** [comment]
播放前获取？

**Comment by MIkeeJY** [comment]
![image](https://user-images.githubusercontent.com/8580762/66906575-87e1c380-f03a-11e9-8480-d96448479e9b.png)
类似这种  @dueeeke

**Comment by dueeeke** [comment]
叫后台返回，播放器没播放之前是拿不到视频的信息的

**Comment by MIkeeJY** [comment]
晓得了~
