### ISSUE TITLE
抖音播放刷新列表后导致视频播放出现问题

### ISSUE THREAD

**Issue by BarkSheep** [dueeeke/DKVideoPlayer#358]
实现功能如点赞视频后 调用notifyItemChanged(int position);更新页面 会造成视频无法继续播放。

notifyItemChanged();方法调用后会使ViewPagerLayoutManager下的RecyclerView.OnChildAttachStateChangeListener中的方法生效。

我尝试修改其中的方法，例如onChildViewDetachedFromWindow(View view)中mDrift(位移)为0时禁止调用mVideoView.release();。有时会起作用 但是会因为 onChildViewAttachedToWindow(View view)中的getChildCount()=2 而无法调用onInitComplete()方法进行startPlay()。而停止播放，并且会造成页面闪烁。
我在刷新后手动进行mVideoView.release(); startPlay(); 也没有作用  

想请教一下作者，有没有好的更新视频item的方法  十分感谢

**Comment by dueeeke** [comment]
点击的时候记录点赞按钮，请求完接口后直接刷新该按钮和数据不就行了，干嘛非要notifyItemChanged

**Comment by BarkSheep** [comment]
妙 妙啊 想了很多解决方法 唯独妹想到这个  十分感谢

**Comment by Zhangxd77** [comment]
我想问下，那我这个比如点关注，可能有多个用户发了视频，上一页下一页也是这个用户，我怎么刷新他的数据，我现在一notify画面就不动了

**Comment by BarkSheep** [comment]
我是将关注的用户id放到了一个HashSet里面   正常加载的时候循环遍历一下判断是否关注  在视频列表里面点了关注之后  遍历ViewPager   具体方法在UpdateControl()里面
/**
     * 关注视频作者成功
     * 1234 5 6789
     * 假设100个item中有20个用户A发的视频 在其中一个Item中关注了用户A 则将用户A
     * 的ID添加到attention中 用于关注按钮的显示与否判断 由于viewpage进行了前四后四
     * 的预加载 所以 遍历前四后四 设置他们的控件状态
     *
     * @param msg
     */
  @Override
    public void focusvideoauthor(String msg, int position) {
        setData(position, 1);
    }

//已关注的用户列表
    private HashSet<String> attention;

  /**
     * 修改可能被预加载的数据
     *
     * @param position 当前操作的视频下标
     * @param isFocus  0未关注 1已关注
     */
    private void setData(int position, int isFocus) {
        Set<Integer> setPosition = new HashSet<>();
        int max = mVideoListBeans.size() > position + 5 ? position + 5 : mVideoListBeans.size();
        //遍历可能被预加载的数据
        for (int i = position > 3 ? position - 4 : 0; i < max; i++) {
            //遍历的数据和指定的数据userId相同时 设置该userId的关注状态
            if (mVideoListBeans.get(position).getAuthorUser().getId().equals(mVideoListBeans.get(i).getAuthorUser().getId())) {
                mVideoListBeans.get(i).getAuthorUser().setIsFocus(isFocus);
                setPosition.add(i);
            }
        }
        UpdateControl(setPosition, isFocus);
        if (isFocus == 0) {
            attention.remove(mVideoListBeans.get(position).getAuthorUser().getId());
        } else {
            attention.add(mVideoListBeans.get(position).getAuthorUser().getId());
        }
        mTiktokAdapter.notifyDataSetChanged();
    }

 /**
     * 更新控件 关注用户专用
     */
    private void UpdateControl(Set<Integer> position, int isFocus) {
        int count = mViewPager.getChildCount();
        for (int i = 0; i < count; i++) {
            View itemView = mViewPager.getChildAt(i);
            TiktokAdapter.ViewHolder viewHolder = (TiktokAdapter.ViewHolder) itemView.getTag();
            if (position.contains(viewHolder.mPosition)) {
                if (isFocus == 0) {
                    viewHolder.tvAttention.setVisibility(View.VISIBLE);
                } else {
                    viewHolder.tvAttention.setVisibility(View.GONE);
                }
            }
        }
    }

**Comment by BarkSheep** [comment]
> 我想问下，那我这个比如点关注，可能有多个用户发了视频，上一页下一页也是这个用户，我怎么刷新他的数据，我现在一notify画面就不动了

我是将关注的用户id放到了一个HashSet里面 正常加载的时候循环遍历一下判断是否关注 在视频列表里面点了关注之后 遍历ViewPager 具体方法在UpdateControl()里面
/**
* 关注视频作者成功
* 1234 5 6789
* 假设100个item中有20个用户A发的视频 在其中一个Item中关注了用户A 则将用户A
* 的ID添加到attention中 用于关注按钮的显示与否判断 由于viewpage进行了前四后四
* 的预加载 所以 遍历前四后四 设置他们的控件状态
*
* @param msg
*/
@override
public void focusvideoauthor(String msg, int position) {
setData(position, 1);
}

//已关注的用户列表
private HashSet attention;

/**
* 修改可能被预加载的数据
*
* @param position 当前操作的视频下标
* @param isFocus 0未关注 1已关注
*/
private void setData(int position, int isFocus) {
Set setPosition = new HashSet<>();
int max = mVideoListBeans.size() > position + 5 ? position + 5 : mVideoListBeans.size();
//遍历可能被预加载的数据
for (int i = position > 3 ? position - 4 : 0; i < max; i++) {
//遍历的数据和指定的数据userId相同时 设置该userId的关注状态
if (mVideoListBeans.get(position).getAuthorUser().getId().equals(mVideoListBeans.get(i).getAuthorUser().getId())) {
mVideoListBeans.get(i).getAuthorUser().setIsFocus(isFocus);
setPosition.add(i);
}
}
UpdateControl(setPosition, isFocus);
if (isFocus == 0) {
attention.remove(mVideoListBeans.get(position).getAuthorUser().getId());
} else {
attention.add(mVideoListBeans.get(position).getAuthorUser().getId());
}
mTiktokAdapter.notifyDataSetChanged();
}

/**
* 更新控件 关注用户专用
*/
private void UpdateControl(Set position, int isFocus) {
int count = mViewPager.getChildCount();
for (int i = 0; i < count; i++) {
View itemView = mViewPager.getChildAt(i);
TiktokAdapter.ViewHolder viewHolder = (TiktokAdapter.ViewHolder) itemView.getTag();
if (position.contains(viewHolder.mPosition)) {
if (isFocus == 0) {
viewHolder.tvAttention.setVisibility(View.VISIBLE);
} else {
viewHolder.tvAttention.setVisibility(View.GONE);
}
}
}
}

**Comment by Zhangxd77** [comment]
不好意思这么久才看见，谢谢你的回答

**Comment by devzwy** [comment]
> 妙 妙啊 想了很多解决方法 唯独妹想到这个 十分感谢

架设当前播放的页面中显示的点赞和收藏数需要登录后查看，我全局的登录状态改变后怎么去做到改变这多个控件呢？

**Comment by Zhangxd77** [comment]
> > 妙 妙啊 想了很多解决方法 唯独妹想到这个 十分感谢
> 
> 架设当前播放的页面中显示的点赞和收藏数需要登录后查看，我全局的登录状态改变后怎么去做到改变这多个控件呢？

你可以按照他说的这个继续写应该可以的吧？只要获取到当前viewpager显示的这页，你就可以获取到控件，就能改了啊

**Comment by devzwy** [comment]
> > > 妙 妙啊 想了很多解决方法 唯独妹想到这个 十分感谢
> > 
> > 
> > 架设当前播放的页面中显示的点赞和收藏数需要登录后查看，我全局的登录状态改变后怎么去做到改变这多个控件呢？
> 
> 你可以按照他说的这个继续写应该可以的吧？只要获取到当前viewpager显示的这页，你就可以获取到控件，就能改了啊

好像不行，这个只是主动的改变数据。我被动的全局刷新登陆状态。要改所有页面的数据。。。。有没有更好的处理方案

**Comment by Brook688** [comment]
不用 notifyItemChanged，下拉刷新，怎么更新数据源
