### ISSUE TITLE
3.1.2版本 将dkplayer-java和dkplayer-ui拷贝到项目里编译报错

### ISSUE THREAD

**Issue by GFL0614** [dueeeke/DKVideoPlayer#359]
3.1.2版本 将dkplayer-java和dkplayer-ui拷贝到项目里 编译正式版时报错   Program type already present: com.dueeeke.videoplayer.controller.BaseVideoController$1

**Comment by dueeeke** [comment]
dkplayer-ui里面也引入了dkplayer-java，把改成api改成compileOnly
