### ISSUE TITLE
继承自StandardVideoController,使用mControllerView.findViewById找不到控件

### ISSUE THREAD

**Issue by dary123** [dueeeke/DKVideoPlayer#363]
public class SendDanmuController extends StandardVideoController<MediaPlayerControl> {
    private RelativeLayout send_danmu_btn;

    private Context mContext;
    public SendDanmuController(@NonNull Context context) {
        super(context);
        mContext = context;
    }

    public SendDanmuController(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    public SendDanmuController(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    protected int getLayoutId() {
        return R.layout.layout_danmu_videoview;
    }

    @Override
    protected void initView() {
        super.initView();
        send_danmu_btn = mControllerView.findViewById(R.id.send_danmu_btn);
        send_danmu_btn.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                new XPopup.Builder(mContext)
                        //.dismissOnBackPressed(false)
                        .autoOpenSoftInput(true)
                        //.moveUpToKeyboard(false) //是否移动到软键盘上面，默认为true
                        .asInputConfirm("输入弹幕内容", "", "",
                                new OnInputConfirmListener() {
                                    @Override
                                    public void onConfirm(String text) {
                                        if (!text.trim().isEmpty()) {
                                            FullScreenSendTxt fsct = new FullScreenSendTxt();
                                            fsct.setContent(text);
                                            EventBus.getDefault().post(fsct);
                                        } else{
                                            CommonUtils.comToast(mContext,"内容不能为空哦");
                                        }
                                    }
                                })
                        .setConfirmText("发送")
                        .show();
            }
        });
    }
}

结果报错：Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

说是send_danmu_btn = mControllerView.findViewById(R.id.send_danmu_btn);这个send_danmu_btn 为null

**Comment by dary123** [comment]
好像是StandardVideoController 类94行
mFullScreenButton = mControllerView.findViewById(R.id.fullscreen);
        mFullScreenButton.setOnClickListener(this);
这个mFullScreenButton 为null

**Comment by dary123** [comment]
是不是我只能继承BaseVideoController，而不能继承StandardVideoController ，但是继承BaseVideoController，就不能设置setLive，setTitle了

**Comment by dueeeke** [comment]
你把StandardVideoController 的布局复制一份放到你项目中，然后在此基础上修改，而不是去重写getLayoutId
