### ISSUE TITLE
同时依赖ijk和exo出现冲突

### ISSUE THREAD

**Issue by wwf1227** [dueeeke/DKVideoPlayer#364]
Execution failed for task ':dkplayer-sample:transformClassesWithDexBuilderForDebug'

**Comment by wwf1227** [comment]
com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\yq\.gradle\caches\transforms-1\files-1.1\exoplayer-hls-2.10.5.aar\2b302b24a8c9c320e7c6fc8775e07600\jars\classes.jar

**Comment by dueeeke** [comment]
使用java8
````
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by wwf1227** [comment]
依赖ijk没有问题   依赖exo会出现冲突
ijk在机型小米8上 倍速播放功能  1.0f以上设置无效果
你的apk用的是exo 在小米8上正常

**Comment by wwf1227** [comment]
加入解决冲突
packagingOptions {
        exclude 'META-INF/proguard/androidx-annotations.pro'
    }

**Comment by dueeeke** [comment]
混淆加一下
