### ISSUE TITLE
播放raw视频，如何处理刚开始播放闪的要给黑屏

### ISSUE THREAD

**Issue by kekekuaile** [dueeeke/DKVideoPlayer#367]

**Comment by dueeeke** [comment]
不太懂你的意思

**Comment by kekekuaile** [comment]
就是播放视频开始有很短的加载时间是黑屏的，能否直接从视频第一帧开始播放




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dueeeke"<notifications@github.com&gt;; 
发送时间: 2019年10月24日(星期四) 晚上6:36
收件人: "dueeeke/DKVideoPlayer"<DKVideoPlayer@noreply.github.com&gt;; 
抄送: "可可快乐"<384572322@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dueeeke/DKVideoPlayer] 播放raw视频，如何处理刚开始播放闪的要给黑屏 (#367)




不太懂你的意思

**Comment by dueeeke** [comment]
播放器总得有个加载过程吧。你可以把视频第一帧截出来，设置成封面图，具体你可以参照抖音demo的做法
