### ISSUE TITLE
使用最新3.1.4版本播放https视频失败

### ISSUE THREAD

**Issue by zaaach** [dueeeke/DKVideoPlayer#368]

**Comment by dueeeke** [comment]
错误日志发一下

**Comment by alanzyz** [comment]
不会也是证书问题吧

**Comment by zaaach** [comment]
`
mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
`
加上上面这行好像是可以播放了
