### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by DancingSnowInFingertips** [dueeeke/DKVideoPlayer#369]
当前进度保存是以播放url为key，个人认为不合适，一般情况是没问题，只不过如果处于安全考虑，后台返回的播放url定时更改，就无法适配了，提出建议，恳请考虑

**Comment by dueeeke** [comment]
那你觉得用什么做key好呢

**Comment by DancingSnowInFingertips** [comment]
可以不需要key，至于获取进度或保存进度让用户自己操作
public abstract class ProgressManager {

    public abstract void saveProgress(long progress);

    public abstract long getSavedProgress();
}

比如，在activity中定义一个当前播放的视频信息变量current,每当视频信息改变就重新给current赋值，则保存进度与获取进度的实现只需要对current操作就可以了

**Comment by dueeeke** [comment]
直接通过getCurrentPosition就能拿到进度
