### ISSUE TITLE
如何混流播放？

### ISSUE THREAD

**Issue by turnmind** [dueeeke/DKVideoPlayer#378]
视频和音频分开的，需要同时播放视频和音频，这个播放器可以实现吗？是否可以从ijkplayer的opensl层播放，播放音频不需要控件，但能同步视频的行为，同步，暂停等

**Comment by dueeeke** [comment]
exoplayer可以实现

**Comment by turnmind** [comment]
@dueeeke 能给个案例吗，谢谢，搜了一圈
