### ISSUE TITLE
预加载问题

### ISSUE THREAD

**Issue by HitenDev** [dueeeke/DKVideoPlayer#379]
抖音预加载那个，快速滑动列表，个别item播放器会抛出异常，报错原因应该是videoCache会生成size为0的缓存文件，看一下截图
![image](https://user-images.githubusercontent.com/7619764/68385553-02fb4d00-0195-11ea-8af6-b1177712d2ff.png)

**Comment by dueeeke** [comment]
确实会这样，应该是因为抖音的视频访问不够稳定，我在PreloadManager也做了容错处理，但是还是无法杜绝
