### ISSUE TITLE
全屏播放崩溃

### ISSUE THREAD

**Issue by luorou** [dueeeke/DKVideoPlayer#385]
The specified child already has a parent. You must call removeView() on the child's parent first.
1	android.view.ViewGroup.addViewInner(ViewGroup.java:4457)
2	android.view.ViewGroup.addView(ViewGroup.java:4298)
3	android.view.ViewGroup.addView(ViewGroup.java:4238)
4	android.view.ViewGroup.addView(ViewGroup.java:4211)
5	com.dueeeke.videoplayer.player.VideoView.stopFullScreen(VideoView.java:753)

**Comment by pz-bottle** [comment]
需要在AndroidManifest的Activity注册中加上android:configChanges="keyboardHidden|orientation|screenSize"

**Comment by luorou** [comment]
> 需要在AndroidManifest的Activity注册中加上android:configChanges="keyboardHidden|orientation|screenSize"

有注册，是偶现的,场景是在ViewPager+Fragment里, 退出全屏后有时也会出现视频播放容器mPlayerContainer没有Add到VideoView里的情况

**Comment by pz-bottle** [comment]
这个我就不太清楚了，我使用时全屏奔溃是因为忘记加上面的东西了，加上就ok了

**Comment by dueeeke** [comment]
你有自己改动过源码吗
