### ISSUE TITLE
IjkPlayer视频ffconcat

### ISSUE THREAD

**Issue by zhongzhibin617** [dueeeke/DKVideoPlayer#389]
作者您好，我并没有在您的demo中看到IjkPlayer视频拼接功能(ffconcat),我只看到了那个连续播放的demo,每次release在设置seturl，其实是销毁当前视频组件重新创建，中间会有过度期（黑屏）,达不到ExoPlayer的concatsource的直接播放一个队列，中间连贯不会有切换的黑屏，麻烦请教下，我对ffmpeg的用法还不是很熟悉，有时间麻烦解答一下吧，万分感谢，我目前项目还是用的MediaPlayer硬解，用的setNextMediaPlayer来实现视频的无缝切换

**Comment by dueeeke** [comment]
在自定义ijkPlayer这个demo里面
