### ISSUE TITLE
安卓Q无法播放本地视频  显示permission dead   求解决

### ISSUE THREAD

**Issue by a871521119** [dueeeke/DKVideoPlayer#398]
我这边是请求过权限的   
![37)R9M}V(7B7PE BOC GQ1E](https://user-images.githubusercontent.com/19202511/69854333-cfa76c00-12c3-11ea-96ff-3e1e4e90f0d9.png)

**Comment by a871521119** [comment]
其他的安卓版本都是可以的

**Comment by dueeeke** [comment]
https://developer.android.com/training/data-storage/files/external-scoped?hl=zh_cn
