### ISSUE TITLE
release();黑屏啦

### ISSUE THREAD

**Issue by HeroBarry** [dueeeke/DKVideoPlayer#401]
播放状态下mVideoView.release();之后页面黑屏；未知发生什么了，EXO和ijk都一样黑屏。

现在想要的场景是正在播放一个普通视频，强制切换为一个VIP视频。请大神帮忙看看怎么处理

**Comment by HeroBarry** [comment]
遇到麻烦啦  改的东西找到位置啦

**Comment by lovewysy** [comment]
> 



> 遇到麻烦啦 改的东西找到位置啦

改的哪里呢，请问一下。我现在也是一样有上次的残影没关系。就是不能黑屏
