### ISSUE TITLE
抖音快速滑动按home键退到后台音频仍在播放

### ISSUE THREAD

**Issue by hueyoung** [dueeeke/DKVideoPlayer#402]
原因是prepareAsync播放，onpause的时调用pause或者stop无法暂停视频，如何解？

**Comment by dueeeke** [comment]
监听state_playing，然后手动暂停

**Comment by lushu4** [comment]
> 

抖音模式播放，后台打开activity，有时候监听拿不到回调STATE_PLAYING但是能拿到STATE_PREPARED和STATE_PREPARING
