### ISSUE TITLE
出了点小问题，请稍后重试

### ISSUE THREAD

**Issue by tanfangliang** [dueeeke/DKVideoPlayer#404]
抖音模块总是出现“出了点小问题，请稍后重试”提示，视频播放不了，DEBUG模式。

**Comment by SUHONGJIN** [comment]
对，我的也是这样

**Comment by tanfangliang** [comment]
抱歉，查了半天是视频源的问题，抖音视频的播放地址失效了。

**Comment by SUHONGJIN** [comment]
兄弟，你做的抖音有用到viewpager+fragment吗，切换时你是怎么释放视频的，可以教教我吗，或者给个demo瞧瞧哈哈
