### ISSUE TITLE
BufferQueue has been abandoned

### ISSUE THREAD

**Issue by tmacbo** [dueeeke/DKVideoPlayer#407]
我在部分机型上碰到了全屏时报“BufferQueue has been abandoned”，由列表小屏切换大屏后，TextureRenderView会调用release 释放掉，导致不能全屏

**Comment by dueeeke** [comment]
部分机型是指什么机型，还有你加了android:configChanges="orientation|screenSize|keyboardHidden"吗

**Comment by tmacbo** [comment]
加了config，在小米8以及一款Android 10的机器上出现
