### ISSUE TITLE
Some .m3u8 videos are not playing

### ISSUE THREAD

**Issue by dheerajbred** [dueeeke/DKVideoPlayer#408]
Hi,

I am using the player to .m3u8 format. It does support and it is working for videos like http://playertest.longtailvideo.com/adaptive/oceans_aes/oceans_aes.m3u8

but my videos like https://node6.vidstreampng.xyz/hls/cb17a5ac69fbbdf8fe8295b401a76f83/cb17a5ac69fbbdf8fe8295b401a76f83.m3u8 is not working. It is showing "Something went wrong. Please try again later". The file is working fine. I checked it on https://castr.io/hlsplayer and it works. But it doesn't play in the DKplayer for some reason. 

![image](https://user-images.githubusercontent.com/46578244/70738448-b5957100-1d3a-11ea-9fdc-b4b11221c8bf.png)
![image](https://user-images.githubusercontent.com/46578244/70738480-c645e700-1d3a-11ea-8685-13cc17236f15.png)

Please help

**Comment by dueeeke** [comment]
我这可以正常播放，请检查你的网络连接
