### ISSUE TITLE
视频黑边的问题

### ISSUE THREAD

**Issue by 799837663** [dueeeke/DKVideoPlayer#413]
is:issue is:open 关于视频播放显示黑边，控件的大小FrameLayout设置150dp和视频比例不对，应该怎么处理？

**Comment by fishflay** [comment]
我也遇到同样的问题，我的想法是将视频虚化作为背景全屏播放然后前台视频正常播放，可惜当前播放器不支持背景虚化播放，希望作者可以增加这个功能以及视频滤镜处理，隔壁的GSYVideoPlayer有这些功能

**Comment by 799837663** [comment]
我的需求是按照微信朋友圈的视频播放，有竖屏和横屏的小视频，你的控件大小和视频比例不一致，目前的解决方案是设置view的SCREEN_SCALE_MATCH_PARENT，铺满父控件FrameLayout设置150d，这样就不会有黑边；还需要判断视频是不是竖屏的，宽高大于高度的比例；

**Comment by fishflay** [comment]
没错，我的项目中videoview大小是固定的，类似抖音那样全屏视频播放，目前我的实现方案是自定义RenderView，重写MeasureHelper.doMeasure（）方法，使视频宽度充满布局，高度按视频比例缩放，这样能实现横屏视频宽度充满布局上下留黑边；竖屏视频宽度充满布局，高度按比例缩放后如果超出布局高度超出的部分不显示如果不超出上下留有黑边    这样就跟抖音显示方案一致了

**Comment by 799837663** [comment]
加个QQ，有问题可以多讨论下

**Comment by dueeeke** [comment]
@fishflay 这功能不在计划之中
