### ISSUE TITLE
How to play a video with response/request header?

### ISSUE THREAD

**Issue by dheerajbred** [dueeeke/DKVideoPlayer#414]
How to play a video with a response/request header?

https://hls10x.cdnfile.info/videos/hls/C5RxlqmwwX56GqXl0YmSfw/1577049940/106359/41683b0af7deebdd046ea58b80082bfb/sub.1.480.m3u8

This video plays only when it is requested with a header
Referer: http://vidstreaming.io/

https://reqbin.com/ screenshot
![image](https://user-images.githubusercontent.com/46578244/71325336-63f69e80-2511-11ea-855c-628c88d0451a.png)

![image](https://user-images.githubusercontent.com/46578244/71325331-504b3800-2511-11ea-8b2b-ff0a890d6827.png)

**Comment by dueeeke** [comment]
setUrl(String url, Map<String, String> headers)
