### ISSUE TITLE
新版用法跟以前不一样了

### ISSUE THREAD

**Issue by dary123** [dueeeke/DKVideoPlayer#415]
继承自StandVideoController的类是不是只能通过下面这个方法获取到layout里的控件:

VodControlView vodControlView = new VodControlView(getContext());
        currNetspeed = vodControlView.findViewById(R.id.curr_netspeed);

还有以前是extends StandardVideoController<MediaPlayerControl> 可以直接获取到播放状态mCurrentPlayerState的，现在该怎么获取

**Comment by dueeeke** [comment]
重写onPlayerStateChanged，自己在子类记录一下mCurrentPlayerState
