### ISSUE TITLE
状态栏沉浸如何实现

### ISSUE THREAD

**Issue by dary123** [dueeeke/DKVideoPlayer#420]
View decorView = getWindow().getDecorView();
        int uiOptions = View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION;
        decorView.setSystemUiVisibility(uiOptions);
无效啊

**Comment by pys200603027** [comment]
这个应该隐藏虚拟按键的代码

**Comment by dueeeke** [comment]
看demo，看源码
