### ISSUE TITLE
请教：如何实现类似B站横竖屏时，controller两套样式

### ISSUE THREAD

**Issue by pys200603027** [dueeeke/DKVideoPlayer#424]
目前想到
1. 在layout中写两个controller的布局，横竖屏幕的时候隐藏和显示（简单，但是代码冗余，而且多处地方，需要同时控制两套布局的展示）
2. 动态添加和删除controller，（灵活，但是数据同步麻烦，比如竖屏中的controller的状态，需要同步到横屏的controller，最简单的seekbar横竖排切换后，不会从0开始计算）

如题，作者有何思路嘛

**Comment by dueeeke** [comment]
多个ControlComponent
