### ISSUE TITLE
在华为荣耀8C上，静音问题

### ISSUE THREAD

**Issue by tmacbo** [dueeeke/DKVideoPlayer#431]
目前发现在华为荣耀的8C上，设置静音了，但是在自动播放的时候，还是会响一声然后才静音

**Comment by dueeeke** [comment]
你在什么时候设置静音的

**Comment by tmacbo** [comment]
VideoViewConfig里面就设定了 静音模式

**Comment by dueeeke** [comment]
你应该用的是很老的版本吧，得你自己去分析，这么老的版本我不维护了
