### ISSUE TITLE
如何隐藏 全屏按钮 ,升级后 mFullScreenButton 控件找不到了

### ISSUE THREAD

**Issue by zj2050** [dueeeke/DKVideoPlayer#432]
升级到 3.2.2后， 从StandardVideoController 继承一个自定义控件，希望隐藏全屏按钮，但现在找不到这个了： mFullScreenButton

    public VideoController(@NonNull Context context) {
        this(context, null);
        this.mFullScreenButton.setVisibility(GONE);
    }

请问现在如何隐藏全屏按钮

谢谢

**Comment by dueeeke** [comment]
看demo, 看源码
