### ISSUE TITLE
全屏状态下，重新播放有的视频会暂停

### ISSUE THREAD

**Issue by tmacbo** [dueeeke/DKVideoPlayer#433]
在全屏状态下，视频播放完成后点击重新播放，视频prepare后有的视频会触发pause，播放暂停

**Comment by tmacbo** [comment]
例如这个视频链接https://v-testing.fenbishuo.com/552a2d476bc70cea3dbba5e3884f4b29.mp4

**Comment by dueeeke** [comment]
请在demo复现一下
