### ISSUE TITLE
支持hls协议吗

### ISSUE THREAD

**Issue by dary123** [dueeeke/DKVideoPlayer#437]
支持hls协议吗

**Comment by dary123** [comment]
像这种NGRjZFlBRCtQSkh4amYrejJBZWp4OUpiQnEyOEJUTXVsT0lSbnduQVNDNHd3TEJ0OURCU2t1dVB3bUFFalZpY0JXc1ZxVXlja01GWURYT0JEYzd1OGZrTFFac0VRWXZJZ3V0S0YzckZtZ2h0cFZEdVFvTkpJWjBHRllpS2xuSmpvOEtXMERzOFRzSTh3MStVdXNtMU9GYTZQNzFUUGVodHBXN1ZxN1JOMVBDOG1sOFhyNlhNSzl5SG5wK08vcDlvUlBOMzZ4dWY3TEszMm5HclhZQzI=

的url支持吗

**Comment by dueeeke** [comment]
支持的
