### ISSUE TITLE
视频播放花屏无声音

### ISSUE THREAD

**Issue by Piscen** [dueeeke/DKVideoPlayer#441]
测试地址 http://tvbilive18-i.akamaihd.net/hls/live/804770/CTVBJ5/CTVBJ5-06.m3u8
直接下载的dmo测试的，换了直播地址。
机型：红米7A
效果：视频是花的，也没有声音，切换了所有播放核心都无法解决

**Comment by dueeeke** [comment]
视频本身就是花屏的
