### ISSUE TITLE
请教断开网络连接优化问题！

### ISSUE THREAD

**Issue by myselyhero** [dueeeke/DKVideoPlayer#442]
你好，目前因为项目需要我也在写视频播放器，遇到一些不懂的地方，想请教一下：
手机断开网络连接后在重新连上网络的时候怎么能够像优酷等视频软件实现自动继续加载并播放呢？

**Comment by dueeeke** [comment]
ijk有断网重连功能，exo需要自己去实现自动重连

**Comment by myselyhero** [comment]
> ijk有断网重连功能，exo需要自己去实现自动重连

，抱歉，有点看不懂，可以说详细一点吗？exo是什么

**Comment by dueeeke** [comment]
看文档，看demo,看源码

**Comment by myselyhero** [comment]
> 看文档，看demo,看源码
好的
