### ISSUE TITLE
无法播放avi

### ISSUE THREAD

**Issue by chinamingsss** [dueeeke/DKVideoPlayer#444]
请问avi格式的视频为什么只有声音没有画面？？

**Comment by dueeeke** [comment]
给我个地址

**Comment by chinamingsss** [comment]
https://testimage.shandianxue.com/85422cb3-fe44-4cb4-9e98-0caf3d1d434b
这个地址




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiantao"<notifications@github.com&gt;; 
发送时间: 2020年1月16日(星期四) 晚上6:17
收件人: "dueeeke/DKVideoPlayer"<DKVideoPlayer@noreply.github.com&gt;; 
抄送: "笑纳人生"<289467139@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dueeeke/DKVideoPlayer] 无法播放avi (#444)




给我个地址

**Comment by chinamingsss** [comment]
https://testimage.shandianxue.com/20200116/fec2527639be4d8097976994d15be5a2.avi
这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiantao"<notifications@github.com&gt;; 
发送时间: 2020年1月16日(星期四) 晚上6:17
收件人: "dueeeke/DKVideoPlayer"<DKVideoPlayer@noreply.github.com&gt;; 
抄送: "笑纳人生"<289467139@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dueeeke/DKVideoPlayer] 无法播放avi (#444)




给我个地址

**Comment by MZCretin** [comment]
@chinamingsss 你解决这个问题了吗
