### ISSUE TITLE
为啥我更新到最新版了，还是会报错Receiver not registered: com.dueeeke.videocontroller.component.TitleView$b@ca80ab6

### ISSUE THREAD

**Issue by dary123** [dueeeke/DKVideoPlayer#451]
为啥我更新到最新版了，还是会报错Receiver not registered: com.dueeeke.videocontroller.component.TitleView$b@ca80ab6

**Comment by dueeeke** [comment]
你自己去看看我写的源码然后再查查原因，我也没办法
