### ISSUE TITLE
大佬，那个demo的连接是不是失效了

### ISSUE THREAD

**Issue by emptyNesterAfter90** [dueeeke/DKVideoPlayer#461]

**Comment by dueeeke** [comment]
没有失效

**Comment by cctxwan** [comment]
链接打开提示404

**Comment by dueeeke** [comment]
确实失效了。用这个http://d.alphaqr.com/1r3u

**Comment by cctxwan** [comment]
好的&nbsp; 谢谢大佬






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dueeeke"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 下午3:57
收件人:&nbsp;"dueeeke/DKVideoPlayer"<DKVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"财财同学"<mr.cai_cai@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [dueeeke/DKVideoPlayer] 大佬，那个demo的连接是不是失效了 (#461)




确实失效了。用这个http://d.alphaqr.com/1r3u

**Comment by emptyNesterAfter90** [comment]
谢谢

**Comment by cctxwan** [comment]
大佬&nbsp; 这个播放器的状态我有一点弄不明白，能不能把我看一下；QQ：486789970




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"emptyNesterAfter90"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 下午4:06
收件人:&nbsp;"dueeeke/DKVideoPlayer"<DKVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"财财同学"<mr.cai_cai@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [dueeeke/DKVideoPlayer] 大佬，那个demo的连接是不是失效了 (#461)




谢谢
