### ISSUE TITLE
手势操作开关，没有起作用！

### ISSUE THREAD

**Issue by eekidu** [dueeeke/DKVideoPlayer#462]
com.dueeeke.videoplayer.controller.GestureVideoController#mIsGestureEnabled
这个开关并并没有阻止触摸事件传递到手势识别器中。
onTouch(View v, MotionEvent event)中应该做一些处理。

**Comment by dueeeke** [comment]
这个开关又不是干这个用的，具体用处看代码的注释，你既然不想要手势就直接继承BaseVideoController去实现代码
