### ISSUE TITLE
播放完成后没有保存进度

### ISSUE THREAD

**Issue by DancingSnowInFingertips** [dueeeke/DKVideoPlayer#464]
如题，播放完成的回调没有保存进度
我遇到的问题：第一次进来接着上次进度继续播放，播放完成后，返回再进这个页面，还是从之前的进度开始播放

**Comment by dueeeke** [comment]
demo能复现吗，我自己测试正常啊

**Comment by DancingSnowInFingertips** [comment]
不好意思哈，是我的问题，你是在播放完成后做了进度清理的
![image](https://user-images.githubusercontent.com/32406771/76046429-da486000-5f9a-11ea-8568-3d429d416e73.png)
