### ISSUE TITLE
在VideoView.setLooping(true)的时候，如何判断视频已经播放完一次了

### ISSUE THREAD

**Issue by luyuan11233** [dueeeke/DKVideoPlayer#466]
在VideoView.setLooping(true)的时候，如何判断视频已经播放完一次了，尝试了很多办法

**Comment by pys200603027** [comment]
用map<String,Integer>记录<url,次数> ,在onPlayComplete这种事件完成后，次数+1

**Comment by dueeeke** [comment]
无法判断
