### ISSUE TITLE
仿Tiktok播放视频

### ISSUE THREAD

**Issue by liang979zhang** [dueeeke/DKVideoPlayer#469]
仿Tiktok播放视频,在循环播放某个视频的时候,画面卡住,声音还是继续播放

![358646f46f86e26966a406f6f23a9596 (1)](https://user-images.githubusercontent.com/16227667/76820156-4487bd00-6845-11ea-83f7-f24d37bc0203.gif)

**Comment by dueeeke** [comment]
哪个播放器
