### ISSUE TITLE
exo内核无法播放

### ISSUE THREAD

**Issue by ccflyy** [dueeeke/DKVideoPlayer#471]
http://mlive1.91kds.cn/b9/shydbst.m3u8?id=cctv1&nwtime=1584533331&sign=b5d325911c8a258513c7d55a2fab83ba&mip=122.191.133.233&from=com

**Comment by dueeeke** [comment]
你这地址本身就播不出来

**Comment by ccflyy** [comment]
试了下，手机用mx播放器可以播放
