### ISSUE TITLE
你好，使用exo时设置缓冲时间有时出错

### ISSUE THREAD

**Issue by ccflyy** [dueeeke/DKVideoPlayer#475]
public class ExoMediaPlayerFactory extends PlayerFactory<ExoMediaPlayer> {

    public static ExoMediaPlayerFactory create() {
        return new ExoMediaPlayerFactory();
    }

    @Override
    public ExoMediaPlayer createPlayer(Context context) {
        ExoMediaPlayer player=new ExoMediaPlayer(context);
        player.setLoadControl(new DefaultLoadControl.Builder()
                .setBufferDurationsMs(1000*60*6, 1000*60*8,1500,2000)
                .createDefaultLoadControl());
        return player;
    }
}

大部分时候滑动屏幕快进时，原有缓冲进度会清零，又重新开始缓冲

**Comment by dueeeke** [comment]
这个是正常现象，exoplayer默认行为就是seek之后原有缓冲进度清零

**Comment by ccflyy** [comment]
请问可以设置不清零吗

**Comment by dueeeke** [comment]
开启exo的缓存即可

**Comment by dary123** [comment]
> 开启exo的缓存即可

怎么开启exo的缓存

**Comment by SuperZhouyong** [comment]
这么设置缓冲，第二个进度条显示不正常。

public class ZyExoMediaPlayerFactory extends PlayerFactory<ExoMediaPlayer> {

    public static ExoMediaPlayerFactory create() {
        return new ExoMediaPlayerFactory();
    }

    @Override
    public ExoMediaPlayer createPlayer(Context context) {
        ExoMediaPlayer myExoPlayer = new ExoMediaPlayer(context);
        //new DefaultLoadControl.Builder()
        //    //.setBufferDurationsMs(2000 * 4 * 4, 1000 * 5 * 4 * 4, 1500, 2000)
        //    .setBufferDurationsMs(1000 * 60 * 20, 1000 * 60 * 15 * 10, 1500, 2000)
        //    //.setAllocator(new DefaultAllocator(true, 16))
        //    //.setTargetBufferBytes(-1)
        //    //.setPrioritizeTimeOverSizeThresholds(true)
        //    .build();
        myExoPlayer.setLoadControl(new DefaultLoadControl.Builder()
            //.setBufferDurationsMs(2000 * 4 * 4, 1000 * 5 * 4 * 4, 1500, 2000)
            .setBufferDurationsMs(1000 * 60 * 20, 1000 * 60 * 15 * 10, 1500, 2000)
            //.setAllocator(new DefaultAllocator(true, 16))
            //.setTargetBufferBytes(-1)
            //.setPrioritizeTimeOverSizeThresholds(true)
            .build());
        return myExoPlayer;
    }
}

@Doikki @ccflyy @dary123
