### ISSUE TITLE
两个小问题！

### ISSUE THREAD

**Issue by eekidu** [dueeeke/DKVideoPlayer#476]
1.这个开关对双击播放暂停是不起效果的。不知道是注释有误还是故意这么处理的？
`    
com.dueeeke.videoplayer.controller.GestureVideoController#onDoubleTap
/**
     * 是否开启手势空控制，默认开启，关闭之后，**双击播放暂停**以及手势调节进度，音量，亮度功能将关闭
     */
    public void setGestureEnabled(boolean gestureEnabled) {
        mIsGestureEnabled = gestureEnabled;
    }

    /**
     * 双击
     */
    @Override
    public boolean onDoubleTap(MotionEvent e) {
        if (!isLocked() && isInPlaybackState()) togglePlay();
        return true;
    }
`
2. 想要实现类似腾讯视频APP后台播放视频列表的一个功能，但是现在下个视频播放，如果界面不可见，会暂停。这个地方需要放开，想问一下，这里的这个暂停是因为觉得没必要继续播放，还是有因为什么其他原因？单纯的把这里放开会有什么问题吗？
`
com.dueeeke.videoplayer.player.VideoView#onInfo

    @Override
    public void onInfo(int what, int extra) {
        switch (what) {
          ……
            case AbstractPlayer.MEDIA_INFO_VIDEO_RENDERING_START: // 视频开始渲染
                setPlayState(STATE_PLAYING);
                if (mPlayerContainer.getWindowVisibility() != VISIBLE) {
                    pause();
                }
                break;
             ……
        }
    }

`
望指点，多谢

**Comment by dueeeke** [comment]
1.注释有误
2.可以去掉，这个就是为了不让videoview不可见的的时候播放视频
