### ISSUE TITLE
setUrl(String url, Map<String, String> headers)无效

### ISSUE THREAD

**Issue by zhangnin** [dueeeke/DKVideoPlayer#479]
设置Host无效：
Map<String, String> headers = new HashMap<>();
headers.put("Host",“xxxxxxx”);
headers.put("X-Online-Host", "“xxxxxxx”");
setUrl(playUrl, headers);

此处因为使用了阿里云的httpDns，需要在拉视频的时候加上上面两个参数

我看源码里面只处理了User-Agent这个属性：
 //处理UA问题
                if (headers != null) {
                    String userAgent = headers.get("User-Agent");
                    if (!TextUtils.isEmpty(userAgent)) {
                        mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user_agent", userAgent);
                    }
                }

**Comment by dueeeke** [comment]
value前面加个空格，比如headers.put("Host", " vfx.mtime.cn");
