### ISSUE TITLE
kotlin切换核心问题

### ISSUE THREAD

**Issue by supppig** [dueeeke/DKVideoPlayer#482]
mVideoView.setPlayerFactory(IjkPlayerFactory.create());

这句在kotlin中应该怎么写，自己这样写的话，会报错。
Type mismatch: inferred type is IjkPlayerFactory! but Nothing was expected

请大大们指教！

**Comment by dueeeke** [comment]
(mVideoView as VideoView<IjkPlayerFactory>).setPlayerFactory(IjkPlayerFactory.create());
