### ISSUE TITLE
退到后台过一会儿再回到前台  会丢失进度重新播放

### ISSUE THREAD

**Issue by mz5210** [dueeeke/DKVideoPlayer#486]
退到后台过一会儿再回到前台  会丢失进度重新播放

**Comment by mz5210** [comment]
使用的是ijkplayer 错误码-10000

**Comment by dueeeke** [comment]
一会儿是多久

**Comment by mz5210** [comment]
> 一会儿是多久

大概五分钟左右，多次尝试发现应该是内存不足，而且要全屏状态下切出去，然后开几个其他APP玩个5分钟再回来，就会提示重新播放 ijkplayer code -10000
