### ISSUE TITLE
屏幕切换时切换布局

### ISSUE THREAD

**Issue by GXSZone** [dueeeke/DKVideoPlayer#487]
**一.如何实现在正常屏幕和全屏时用两套底部控制**

正常屏幕比较简单和Demo示例基本一致，但是全屏时底部控制布局就复杂一点了，单纯的隐藏和显示比较麻烦和夯余，也是一个笨法子，有没有更好一点的控制方式

**Comment by dueeeke** [comment]
1.再写一个全屏时候的controlcomponent，全屏时显示出来就行了2.没明白你意思

**Comment by GXSZone** [comment]
@dueeeke 就是大多数播放器都会有的，全屏时点击右上角菜单会有个侧边栏放置按钮，亮度，倍速的，用这个怎么做，单写一个View还是写在StandardVideoController里，我在哪写都会影响到触摸事件

**Comment by dueeeke** [comment]
影响控制的触摸事件?

**Comment by GXSZone** [comment]
@dueeeke 对，就是有没有放在那里不影响触摸，点击菜单可以正常显示
