### ISSUE TITLE
3.2.6版本会导致直播无法播放，切回3.2.5版本是可以的

### ISSUE THREAD

**Issue by caiyoufei** [dueeeke/DKVideoPlayer#492]
猜想应该是地址解析导致，使用的直播地址为(具有时效性，可以参考格式)：rtmp://happydev.vgeducation.org:1935/506fa94cca9a40d4a51134b28830fce5/ClKEtNlhy8*d!Gp*P88ApxIdxPmTgJvfsIx8b0kK0bKmkAxAGmh!fZ3aKoMuPHqR?acctoken=36e9a5ea36dcef0eb2210c872ef9fd8a&timestamp=1587560238957

**Comment by dueeeke** [comment]
视频是什么格式，还有能否给一下播放器日志

**Comment by caiyoufei** [comment]
@dueeeke 这个是直播地址，不是视频，是直播流

**Comment by dueeeke** [comment]
直播也有编码格式啊

**Comment by dueeeke** [comment]
你用的哪个播放器，看一下播放器的日志

**Comment by caiyoufei** [comment]
![image](https://user-images.githubusercontent.com/11989916/80330894-b1dd3380-8870-11ea-8c7e-3acdd17e0141.png)

**Comment by caiyoufei** [comment]
我试过Ijk、Exo、原生，好像都不行的感觉

**Comment by caiyoufei** [comment]
![image](https://user-images.githubusercontent.com/11989916/80331097-56f80c00-8871-11ea-995f-25271b5bb009.png)
这是我用VLC直接拉流获取到的

**Comment by dueeeke** [comment]
我查了RtmpClient的源码，返回-6表示dns无法解析[https://github.com/ant-media/LibRtmp-Client-for-Android/blob/master/rtmp-client/src/main/java/net/butterflytv/rtmp_client/RtmpClient.java#L58](url)

**Comment by caiyoufei** [comment]
@dueeeke 好吧，那就跟lib没有关系了，感谢大佬帮忙

**Comment by caiyoufei** [comment]
@dueeeke 
![image](https://user-images.githubusercontent.com/11989916/80332517-3d58c380-8875-11ea-9d29-2088be314763.png)
切换到IJK也会报错，难道只有VLC可以用么

**Comment by dueeeke** [comment]
dns解析有问题，你切到4g网络看看

**Comment by caiyoufei** [comment]
我试试

**Comment by caiyoufei** [comment]
有点神奇啊，2个手机连接同一个WIFI，都没有开启抓包
一个手机死活解析不了，另外一个手机确是可以拉流播放的，我懵逼了
