### ISSUE TITLE
3.2.6拖动seekbar后视频无法播放

### ISSUE THREAD

**Issue by ailuoli0531** [dueeeke/DKVideoPlayer#496]
播放时间还在计时，但视频完全停在拖动前的那一帧了。无自定义，只是根据说明最简单的集成。抱歉无法看demo,最近这网站登录都难，1k/s

**Comment by dueeeke** [comment]
检查一下你的网络，视频这样说明你的网络真的很慢

**Comment by ailuoli0531** [comment]
缓存条显示已经缓存完了，拖动进度条后，连加载中也没有。啊我无法描述了。下载你的demo是正常的，
 videoView.setUrl(URL_VOD); //设置视频地址
        StandardVideoController controller = new StandardVideoController(this);
        controller.addDefaultControlComponent("",false);
        videoView.setVideoController(controller); //设置控制器
        videoView.startFullScreen();
        videoView.setScreenScaleType(VideoView.SCREEN_SCALE_16_9);
        videoView.start(); 
没有多余的东西 我用的4G

**Comment by dueeeke** [comment]
你把地址给我

**Comment by ailuoli0531** [comment]
http://mcnvideo.ertoutiao.com/playbox/drinkWater/jianshen.mp4

**Comment by dueeeke** [comment]
你这视频编码有问题

**Comment by ailuoli0531** [comment]
刚刚试了一些其他视频，大部分视频可以拖动。部分视频即使缓存完成了拖动也要等较长时间。总体来说知道了问题在哪，多谢🙏
附一下各种视频测试地址：
https://www.cnblogs.com/guanxinjing/p/11024016.html
