### ISSUE TITLE
全屏状态下开启悬浮窗

### ISSUE THREAD

**Issue by GXSZone** [dueeeke/DKVideoPlayer#498]
用Demo测试也是一样 全屏状态下开启悬浮窗我没有finish掉当前的activity（finish掉也一样），会有一个悬浮窗，但是就一黑色背景，该显示在悬浮窗的却全屏显示了，

**Comment by dueeeke** [comment]
全屏状态不支持悬浮窗，如果非要支持你自己去改源码

**Comment by GXSZone** [comment]
@dueeeke 好的
