### ISSUE TITLE
如何设置封面图？

### ISSUE THREAD

**Issue by kkkforever1** [dueeeke/DKVideoPlayer#85]
播放本地视频前  如何设置显示封面图？

**Comment by dueeeke** [comment]
使用glide可以显示视频缩略图，或者使用MediaMetadataRetriever

**Comment by PascalTang** [comment]
看不太明白
glide 無法設置在 IjkVideoView上

**Comment by Nicolaszh** [comment]
`  Glide.with(this)
                    .load(thumburl)
                    .placeholder(R.color.cl_default)
                    .error(R.color.cl_error)
                    .into(controller.getThumb());`

**Comment by zj2050** [comment]
@Nicolaszh 如果播放的是mp3， 封面在controller出现后黑屏，不再显示封面图片了
