### ISSUE TITLE
如何全局停止播放

### ISSUE THREAD

**Issue by imagegithub** [dueeeke/DKVideoPlayer#89]
嵌套的fragment,子fragment切换停止解决了，但是父fragment切换的时候还在播放（用的hide 和show）

**Comment by dueeeke** [comment]
在你父fragment切换的的地方调用VideoViewManager.instance().releaseVideoPlayer();就可解决问题

**Comment by imagegithub** [comment]
非常感谢您能回答问题，但是我调用这个方法之后并没有停止，先说明下我的使用情况。我用的是模仿抖音那个模块。Fragment--->FragmentChild------->DouyinViewPager.
在FragmentChild 切换的时候，我在生命周期的setUserVisibleHint进行了操作。
在Fragment切换的时候，我用的hide.同理，我在onHiddenChanged调用了releaseVideoPlayer。这种解决方式无效。我再去翻翻代码看看是什么原因。^-^

**Comment by imagegithub** [comment]
我又看了下需要设置setCurrentVideoPlayer 。

**Comment by dueeeke** [comment]
调用addToPlayerManager()将其添加到VideoViewManager，这样就能全局控制播放器了，或者你可以把播放器封装成单例，这样就可以全局调用了，但要注意内存泄漏
