### ISSUE TITLE
Progress拉到最後

### ISSUE THREAD

**Issue by PascalTang** [dueeeke/DKVideoPlayer#91]
你好
progress bar到最後時
理論上應該要跑出 重新播放的圖
但讓影片自己讀取到最後沒有問題
可是我用手拉時
他就會顯示讀取中的旋轉
然後時常會跑到沒有回應
請問這邊我需要override哪個部分？
這挺嚴重的

**Comment by PascalTang** [comment]
我測試的時候
ts有幾百個
直接拉到底
他一樣回從前面開始 一直讀取
而不會直接跑到最後一個
只有拉到底才有這問題

**Comment by dueeeke** [comment]
这是你视频的原因，关键帧太少

**Comment by PascalTang** [comment]
抱歉 不太明白 关键帧是什麼意思

那我想請問我要複寫哪裡去修正這個問題
因為他只有拉到底會這樣

**Comment by PascalTang** [comment]
好吧我目前用一個爛方法先暫時處理
我在VideoController內
    @Override
    public void setPlayState(int playState) {
//        Log.i("ddd","playState "+playState);
        super.setPlayState(playState);
        if (this.mediaPlayer.getCurrentPosition() == this.mediaPlayer.getDuration()
                && playState == 6
                && this.mediaPlayer.getCurrentPosition() != 0
                && this.mediaPlayer.getDuration() != 0){

            super.setPlayState(5);
//            Log.i("ddd","getCurrentPosition "+mediaPlayer.getCurrentPosition());
//            Log.i("ddd","getDuration "+mediaPlayer.getDuration());
        }
    }

那我現在想知道
要如何stop buffer loading

**Comment by dueeeke** [comment]
把StandardVideoController中的onStopTrackingTouch方法改成如下实现：
    @Override
    public void onStopTrackingTouch(SeekBar seekBar) {
        long duration = mediaPlayer.getDuration();
        int progress = seekBar.getProgress();
        if (progress == 1000) progress = 990;
        long newPosition = (duration * progress) / videoProgress.getMax();
        mediaPlayer.seekTo((int) newPosition);
        isDragging = false;
        post(mShowProgress);
        show();
    }

**Comment by PascalTang** [comment]
嗨 那之後版本isDragging改成protected嗎？
不然extends StandardVideoController無法修改

這做法是參考其他播放器？
拉到底會想讓他往前再播放的原因是什麼

**Comment by PascalTang** [comment]
還有我想問一下 為何常常會發生ANR？
但我用餃子沒這狀況

**Comment by dueeeke** [comment]
你可以试试mediaplayer或者exoplayer，不会有你说的问题
