### ISSUE TITLE
抖音Dome

### ISSUE THREAD

**Issue by chaopengTan** [dueeeke/DKVideoPlayer#92]
如果视频多的话，一直上拉视频，内存开销太大，且无法回收这些内存，因为所有的View都保存在集合里面， 如果用RecyclerView来做，能达到秒开的效果吗

**Comment by dueeeke** [comment]
抖音demo的实现方式确实不太好，我现在已经用RecyclerView重新实现抖音的效果，切到dev分支可以查看
