### ISSUE TITLE
VideoController  TV端 BUG

### ISSUE THREAD

**Issue by nwhhades** [dueeeke/DKVideoPlayer#96]
在给ijkVideoView.setVideoController后会导致Activity无法监听到遥控器的确定键（ action=ACTION_DOWN, keyCode=KEYCODE_ENTER），而其他几个常用键是正常。

检查后发现是VideoController添加的View可以获取焦点并消耗按键事件，导致Activity无法监听按键事件

建议能否添加一种KeyVideoController,适配下TV端的操作，禁止让VideoController里面的控件获取到焦点让点击事件消耗掉确认键。

**Comment by nwhhades** [comment]
自己给出解决办法 -----TV端的兄弟别跑这个还是可以解决的；
```
public abstract class BaseVideoController extends FrameLayout {

    protected View controllerView;//控制器视图
}
```

在BaseVideoController中有一个protected 级的根视图controllerView对象，然后你只要调用一下这个方法

```
public void banishFocus(@NonNull View view){
        view.setFocusable(false);
        view.setFocusableInTouchMode(false);
    }
```
让这个根视图无法获取到焦点，然后你会发现确定键又可以监听到了，然后焦点也正常了

**Comment by firefly5927** [comment]
赞一个。
