### ISSUE TITLE
能够修改Texture 或者surfaceview 成圆角么?

### ISSUE THREAD

**Issue by fujiangren** [dueeeke/DKVideoPlayer#97]
我看了下 似乎没有提供把播放器修改为圆角大方式啊

**Comment by fccaikai** [comment]
我是在外面包了一层CardView,或者自己重写一下IjkVideoView

**Comment by fujiangren** [comment]
重写我也想到了 但是通过源码的学习 发现行不通 后来就是在外面包了 一成 使用的是CircularCoverView
